/**
 * EvidencePack Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import type { components } from "../openapi/audit.openapi.types.js";
/**
 * Entity: EvidencePackEntity
 * Description: Represents the EvidencePack domain model.
 * Source: schemas.EvidencePack
 * Type: Domain Entity (API)
 */
export declare const EvidencePackEntitySchema: any;
export type EvidencePackEntity = components["schemas"]["EvidencePack"];
