/**
 * ExecuteGenerateSettlementInvoice - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGenerateSettlementInvoice Use Case
 *
 * DDD: Application use case for get Invoice.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GenerateSettlementInvoiceInput, GenerateSettlementInvoiceOutput } from "../dto/invoice.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { InvoiceRepository } from "../ports/index.js";
import { NotFoundError, ValidationError } from "../errors/index.js";

export class ExecuteGenerateSettlementInvoice {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly invoice: InvoiceRepository
  ) {}

  async execute(input: GenerateSettlementInvoiceInput): Promise<GenerateSettlementInvoiceOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.stlId();

    // All field names extracted from OpenAPI spec: identityProviderId, period, relyingPartyId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).identityProviderId) {
      throw new ValidationError("identityProviderId is required");
    }
    const identityproviderId = (input as any).identityProviderId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.invoice.generateSettlementInvoice({ identityProviderId: identityproviderId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${identityproviderId}`);
    }

    return entity as GenerateSettlementInvoiceOutput;
  }
}
