/**
 * ExecuteGenerateSettlementInvoice - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { NotFoundError, ValidationError } from "../errors";
export class ExecuteGenerateSettlementInvoice {
    context;
    idGenerator;
    invoice;
    constructor(context, idGenerator, invoice) {
        this.context = context;
        this.idGenerator = idGenerator;
        this.invoice = invoice;
    }
    async execute(input) {
        // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
        const correlationId = this.idGenerator.stlId();
        // All field names extracted from OpenAPI spec: identityProviderId, period, relyingPartyId
        // Validate input
        if (!input) {
            throw new ValidationError("Input is required");
        }
        if (!input.identityProviderId) {
            throw new ValidationError("identityProviderId is required");
        }
        const identityproviderId = input.identityProviderId;
        // Load entity via repository (pass correlation ID for response meta)
        const entity = await this.invoice.generateSettlementInvoice({ identityProviderId: identityproviderId, orgId: this.context.getOrgId(), correlationId });
        if (!entity) {
            throw new NotFoundError(`Entity not found: ${identityproviderId}`);
        }
        return entity;
    }
}
