/**
 * ExecuteListSettlementInvoices - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * ExecuteListSettlementInvoices Use Case
 *
 * DDD: Application use case for list Invoice.
 * Orchestrates the business flow using ports (interfaces).
 */
import type { ListSettlementInvoicesInput, ListSettlementInvoicesOutput } from "../dto/invoice.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { InvoiceRepository } from "../ports/index.js";
export declare class ExecuteListSettlementInvoices {
    private readonly context;
    private readonly idGenerator;
    private readonly invoice;
    constructor(context: ExecutionContextService, idGenerator: IdGeneratorService, invoice: InvoiceRepository);
    execute(input: ListSettlementInvoicesInput): Promise<ListSettlementInvoicesOutput>;
}
