/**
 * ExecuteGetSettlementInvoice - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetSettlementInvoice Use Case
 *
 * DDD: Application use case for get Invoice.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetSettlementInvoiceInput, GetSettlementInvoiceOutput } from "../dto/invoice.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { InvoiceRepository } from "../ports/index.js";
import { NotFoundError, ValidationError } from "../errors/index.js";

export class ExecuteGetSettlementInvoice {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly invoice: InvoiceRepository
  ) {}

  async execute(input: GetSettlementInvoiceInput): Promise<GetSettlementInvoiceOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.stlId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).invoiceId) {
      throw new ValidationError("invoiceId is required");
    }
    const invoiceId = (input as any).invoiceId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.invoice.getSettlementInvoice({ invoiceId: invoiceId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${invoiceId}`);
    }

    return entity as GetSettlementInvoiceOutput;
  }
}
