/**
 * ExecuteGetFeeSchedule - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { NotFoundError, ValidationError } from "../errors";
export class ExecuteGetFeeSchedule {
    context;
    idGenerator;
    feeSchedule;
    constructor(context, idGenerator, feeSchedule) {
        this.context = context;
        this.idGenerator = idGenerator;
        this.feeSchedule = feeSchedule;
    }
    async execute(input) {
        // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
        const correlationId = this.idGenerator.stlId();
        // All field names extracted from OpenAPI spec: none
        // Validate input
        if (!input) {
            throw new ValidationError("Input is required");
        }
        if (!input.scheduleId) {
            throw new ValidationError("scheduleId is required");
        }
        const scheduleId = input.scheduleId;
        // Load entity via repository (pass correlation ID for response meta)
        const entity = await this.feeSchedule.getFeeSchedule({ scheduleId: scheduleId, orgId: this.context.getOrgId(), correlationId });
        if (!entity) {
            throw new NotFoundError(`Entity not found: ${scheduleId}`);
        }
        return entity;
    }
}
