/**
 * DownloadRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * DownloadRepository Port
 *
 * DDD: Application port for downloadrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */
import type { DownloadEvidencePackInput, DownloadEvidencePackOutput } from "../dto/download.dto";
export interface DownloadRepository {
    downloadEvidencePack(input: DownloadEvidencePackInput): Promise<DownloadEvidencePackOutput>;
}
export type { DownloadEvidencePackInput, DownloadEvidencePackOutput } from "../dto/download.dto";
