/**
 * Download DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Download DTOs
 *
 * DDD: Application DTOs for Download use cases.
 */

import type { DownloadEvidencePackParams } from "@kyvora/core/audit/types";

export type DownloadEvidencePackInput = DownloadEvidencePackParams;

export type DownloadEvidencePackOutput = {};
