/**
 * EvidencePack DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EvidencePack DTOs
 *
 * DDD: Application DTOs for EvidencePack use cases.
 */

import type { GenerateEvidencePackRequestInput, GetEvidencePackParams, ListEvidencePacksParams } from "@kyvora/core/audit/types";

export type ListEvidencePacksInput = ListEvidencePacksParams;

export type GenerateEvidencePackInput = GenerateEvidencePackRequestInput;

export type GetEvidencePackInput = GetEvidencePackParams;

export type ListEvidencePacksOutput = {};

export type GenerateEvidencePackOutput = {};

export type GetEvidencePackOutput = {};
