/**
 * LegalEntityLinkRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LegalEntityLinkRepository Port
 *
 * DDD: Application port for legalentitylinkrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateLegalEntityLinkInput, CreateLegalEntityLinkOutput, ListLegalEntityLinksInput, ListLegalEntityLinksOutput, UnlinkLegalEntityInput, UnlinkLegalEntityOutput } from "../dto/legal-entity-link.dto";
export interface LegalEntityLinkRepository {
  listLegalEntityLinks(input: ListLegalEntityLinksInput): Promise<ListLegalEntityLinksOutput>;
  createLegalEntityLink(input: CreateLegalEntityLinkInput): Promise<CreateLegalEntityLinkOutput>;
  unlinkLegalEntity(input: UnlinkLegalEntityInput): Promise<UnlinkLegalEntityOutput>;
}

export type { CreateLegalEntityLinkInput, CreateLegalEntityLinkOutput, ListLegalEntityLinksInput, ListLegalEntityLinksOutput, UnlinkLegalEntityInput, UnlinkLegalEntityOutput } from "../dto/legal-entity-link.dto";
