/**
 * RefreshCycleRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RefreshCycleRepository Port
 *
 * DDD: Application port for refreshcyclerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateRefreshCycleInput, CreateRefreshCycleOutput, ListRefreshCyclesInput, ListRefreshCyclesOutput } from "../dto/refresh-cycle.dto";
export interface RefreshCycleRepository {
  listRefreshCycles(input: ListRefreshCyclesInput): Promise<ListRefreshCyclesOutput>;
  createRefreshCycle(input: CreateRefreshCycleInput): Promise<CreateRefreshCycleOutput>;
}

export type { CreateRefreshCycleInput, CreateRefreshCycleOutput, ListRefreshCyclesInput, ListRefreshCyclesOutput } from "../dto/refresh-cycle.dto";
