/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the subjects domain.
 * Use these factories in tests to create test data.
 */

export { createLegalEntityLink } from "./legal-entity-link/entity/legal-entity-link.entity.factory.js";
export { createRefreshCycle } from "./refresh-cycle/entity/refresh-cycle.entity.factory.js";
