/**
 * Handlers for InvalidateDependent
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: screening
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ScreeningDomainModule } from "../dependencies/screening-ddd.dependencies.js";
import type { InvalidateStaleScreeningDependentsInput } from "@kyvora/services/screening";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/screening/snapshots/{snapshotId}/invalidate-dependents
 * Operation: invalidateStaleScreeningDependents
 */
export async function invalidateStaleScreeningDependents(
  request: FastifyRequest<{ Params: { snapshotId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ScreeningDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: InvalidateStaleScreeningDependentsInput = {
    snapshotId: request.params.snapshotId,
  };
  const result = await deps.useCases.invalidateDependents.get.execute(input);
  return reply.code(200).send(result);
}


