/**
 * Directory DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Directory Domain Module - Composition root
 *
 * DDD: Composition root for directory domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CertifyRepositoryAdapter,
  IdentityProviderRepositoryAdapter,
  MembershipDecisionRepositoryAdapter,
  RelyingPartyRepositoryAdapter,
  SuspendRepositoryAdapter,
} from "@kyvora/adapters/directory";
import { getIdGeneratorService } from "@kyvora/adapters";
import type { AdapterDynamoDBClient } from "@kyvora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCertifyIdentityProvider,
  ExecuteCertifyRelyingParty,
  ExecuteGetIdentityProvider,
  ExecuteGetRelyingParty,
  ExecuteListIdentityProviders,
  ExecuteListMembershipDecisions,
  ExecuteListRelyingParties,
  ExecuteRegisterIdentityProvider,
  ExecuteRegisterRelyingParty,
  ExecuteSuspendIdentityProvider,
  ExecuteSuspendRelyingParty,
} from "@kyvora/services/directory/usecases";
// Ports (interfaces)
import type {
  CertifyRepository,
  IdentityProviderRepository,
  MembershipDecisionRepository,
  RelyingPartyRepository,
  SuspendRepository,
} from "@kyvora/services/directory/ports";

export interface DirectoryDomainModule {
  repos: {
    certifies: CertifyRepository;
    identityProviders: IdentityProviderRepository;
    membershipDecisions: MembershipDecisionRepository;
    relyingParties: RelyingPartyRepository;
    suspends: SuspendRepository;
  };
  useCases: {
    certifies: {
      get: ExecuteCertifyRelyingParty;
    };
    identityProviders: {
      create: ExecuteRegisterIdentityProvider;
      get: ExecuteGetIdentityProvider;
      list: ExecuteListIdentityProviders;
    };
    membershipDecisions: {
      list: ExecuteListMembershipDecisions;
    };
    relyingParties: {
      create: ExecuteRegisterRelyingParty;
      get: ExecuteGetRelyingParty;
      list: ExecuteListRelyingParties;
    };
    suspends: {
      get: ExecuteSuspendRelyingParty;
    };
  };
}

export function buildDirectoryDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): DirectoryDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      certifies?: CertifyRepository;
      identityProviders?: IdentityProviderRepository;
      membershipDecisions?: MembershipDecisionRepository;
      relyingParties?: RelyingPartyRepository;
      suspends?: SuspendRepository;
    } = {};

    obj.certifies = new CertifyRepositoryAdapter(dynamoClient);
    obj.identityProviders = new IdentityProviderRepositoryAdapter(dynamoClient);
    obj.membershipDecisions = new MembershipDecisionRepositoryAdapter(dynamoClient);
    obj.relyingParties = new RelyingPartyRepositoryAdapter(dynamoClient);
    obj.suspends = new SuspendRepositoryAdapter(dynamoClient);
    return {
      certifies: obj.certifies!,
      identityProviders: obj.identityProviders!,
      membershipDecisions: obj.membershipDecisions!,
      relyingParties: obj.relyingParties!,
      suspends: obj.suspends!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    certifies: {
      get: new ExecuteCertifyRelyingParty(executionContext, idGenerator, repos.certifies),
    },
    identityProviders: {
      create: new ExecuteRegisterIdentityProvider(executionContext, idGenerator, repos.identityProviders),
      get: new ExecuteGetIdentityProvider(executionContext, idGenerator, repos.identityProviders),
      list: new ExecuteListIdentityProviders(executionContext, idGenerator, repos.identityProviders),
    },
    membershipDecisions: {
      list: new ExecuteListMembershipDecisions(executionContext, idGenerator, repos.membershipDecisions),
    },
    relyingParties: {
      create: new ExecuteRegisterRelyingParty(executionContext, idGenerator, repos.relyingParties),
      get: new ExecuteGetRelyingParty(executionContext, idGenerator, repos.relyingParties),
      list: new ExecuteListRelyingParties(executionContext, idGenerator, repos.relyingParties),
    },
    suspends: {
      get: new ExecuteSuspendRelyingParty(executionContext, idGenerator, repos.suspends),
    },
  };
  return { repos, useCases: useCases as DirectoryDomainModule["useCases"] };
}
