/**
 * GetConsent DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetConsentGrantParams } from "@kyvora/core/consents";

export function createGetConsentRequest(overrides: Partial<GetConsentGrantParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
