/**
 * FeeSchedule Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import type { components } from "../openapi/settlement.openapi.types.js";
/**
 * Entity: FeeScheduleEntity
 * Description: Represents the FeeSchedule domain model.
 * Source: schemas.FeeSchedule
 * Type: Domain Entity (API)
 */
export declare const FeeScheduleEntitySchema: any;
export type FeeScheduleEntity = components["schemas"]["FeeSchedule"];
