/**
 * IdentityProvider Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import type { components } from "../openapi/directory.openapi.types.js";
/**
 * Entity: IdentityProviderEntity
 * Description: Represents the IdentityProvider domain model.
 * Source: schemas.IdentityProvider
 * Type: Domain Entity (API)
 */
export declare const IdentityProviderEntitySchema: any;
export type IdentityProviderEntity = components["schemas"]["IdentityProvider"];
