/**
 * MembershipDecision Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import type { components } from "../openapi/directory.openapi.types.js";
/**
 * Entity: MembershipDecisionEntity
 * Description: Represents the MembershipDecision domain model.
 * Source: schemas.MembershipDecision
 * Type: Domain Entity (API)
 */
export declare const MembershipDecisionEntitySchema: any;
export type MembershipDecisionEntity = components["schemas"]["MembershipDecision"];
