/**
 * RelyingParty Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/directory.openapi.types.js";
import { schemas } from "../schemas/directory.schemas.js";

/**
 * Entity: RelyingPartyEntity
 * Description: Represents the RelyingParty domain model.
 * Source: schemas.RelyingParty
 * Type: Domain Entity (API)
 */
export const RelyingPartyEntitySchema = schemas.RelyingParty;
export type RelyingPartyEntity = components["schemas"]["RelyingParty"];
