/**
 * Handlers for Suspend
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DirectoryDomainModule } from "../dependencies/directory-ddd.dependencies.js";
import type { SuspendIdentityProviderInput, SuspendRelyingPartyInput } from "@kyvora/services/directory";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/directory/identity-providers/{idpId}/suspend
 * Operation: suspendIdentityProvider
 */
export async function suspendIdentityProvider(
  request: FastifyRequest<{ Params: { idpId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DirectoryDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SuspendIdentityProviderInput = {
    idpId: request.params.idpId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.suspends.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/directory/relying-parties/{rpId}/suspend
 * Operation: suspendRelyingParty
 */
export async function suspendRelyingParty(
  request: FastifyRequest<{ Params: { rpId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DirectoryDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SuspendRelyingPartyInput = {
    rpId: request.params.rpId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.suspends.get.execute(input);
  return reply.code(200).send(result);
}


