/**
 * Attestation DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Attestation DTOs
 *
 * DDD: Application DTOs for Attestation use cases.
 */

import type { GetAttestationParams, ListAttestationsParams, RequestAttestationRequestInput } from "@kyvora/core/attestations/types";

export type ListAttestationsInput = ListAttestationsParams;

export type RequestAttestationInput = RequestAttestationRequestInput;

export type GetAttestationInput = GetAttestationParams;

export type ListAttestationsOutput = {};

export type RequestAttestationOutput = {};

export type GetAttestationOutput = {};
