/**
 * DocumentRecollectException DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * DocumentRecollectException DTOs
 *
 * DDD: Application DTOs for DocumentRecollectException use cases.
 */
import type { RecordDocumentRecollectExceptionParams, RecordDocumentRecollectExceptionRequestInput } from "@kyvora/core/attestations/types";
export type RecordDocumentRecollectExceptionInput = RecordDocumentRecollectExceptionParams & RecordDocumentRecollectExceptionRequestInput;
export type RecordDocumentRecollectExceptionOutput = {};
