/**
 * Issue DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * Issue DTOs
 *
 * DDD: Application DTOs for Issue use cases.
 */
import type { IssueAttestationParams, IssueAttestationRequestInput } from "@kyvora/core/attestations/types";
export type IssueAttestationInput = IssueAttestationParams & IssueAttestationRequestInput;
export type IssueAttestationOutput = {};
