/**
 * Dispute DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Dispute DTOs
 *
 * DDD: Application DTOs for Dispute use cases.
 */

import type { GetDisputeCaseParams, ListDisputeCasesParams, OpenDisputeCaseRequestInput } from "@kyvora/core/disputes/types";

export type ListDisputeCasesInput = ListDisputeCasesParams;

export type OpenDisputeCaseInput = OpenDisputeCaseRequestInput;

export type GetDisputeCaseInput = GetDisputeCaseParams;

export type ListDisputeCasesOutput = {};

export type OpenDisputeCaseOutput = {};

export type GetDisputeCaseOutput = {};
