/**
 * ListMembershipDecisions handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listMembershipDecisions } from "@kyvora/api-server/domains/directory/handlers";
import type { DirectoryDDDDependencies } from "@kyvora/api-server/domains/directory";
import { createMembershipDecision as createMembershipDecisionEntity } from "@kyvora/factories/directory";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@kyvora/tests/shared";
import { DIRECTORY_USE_CASES } from "../__factories__/use-cases.js";

describe("ListMembershipDecisions", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DirectoryDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DirectoryDDDDependencies>(
      DIRECTORY_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createMembershipDecisionEntity({ orgId }),
      createMembershipDecisionEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListMembershipDecisions, "execute").mockResolvedValue(useCaseResult);

    await listMembershipDecisions(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListMembershipDecisions.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
