/**
 * ExecuteListIdentityProviders - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * ExecuteListIdentityProviders Use Case
 *
 * DDD: Application use case for list IdentityProvider.
 * Orchestrates the business flow using ports (interfaces).
 */
import type { ListIdentityProvidersInput, ListIdentityProvidersOutput } from "../dto/identity-provider.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { IdentityProviderRepository } from "../ports/index.js";
export declare class ExecuteListIdentityProviders {
    private readonly context;
    private readonly idGenerator;
    private readonly identityProvider;
    constructor(context: ExecutionContextService, idGenerator: IdGeneratorService, identityProvider: IdentityProviderRepository);
    execute(input: ListIdentityProvidersInput): Promise<ListIdentityProvidersOutput>;
}
