/**
 * ExecuteListMembershipDecisions - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * ExecuteListMembershipDecisions Use Case
 *
 * DDD: Application use case for list MembershipDecision.
 * Orchestrates the business flow using ports (interfaces).
 */
import type { ListMembershipDecisionsInput, ListMembershipDecisionsOutput } from "../dto/membership-decision.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { MembershipDecisionRepository } from "../ports/index.js";
export declare class ExecuteListMembershipDecisions {
    private readonly context;
    private readonly idGenerator;
    private readonly membershipDecision;
    constructor(context: ExecutionContextService, idGenerator: IdGeneratorService, membershipDecision: MembershipDecisionRepository);
    execute(input: ListMembershipDecisionsInput): Promise<ListMembershipDecisionsOutput>;
}
