/**
 * ExecuteCertifyIdentityProvider - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * ExecuteCertifyIdentityProvider Use Case
 *
 * DDD: Application use case for get Certify.
 * Orchestrates the business flow using ports (interfaces).
 */
import type { CertifyIdentityProviderInput, CertifyIdentityProviderOutput } from "../dto/certify.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { CertifyRepository } from "../ports/index.js";
export declare class ExecuteCertifyIdentityProvider {
    private readonly context;
    private readonly idGenerator;
    private readonly certify;
    constructor(context: ExecutionContextService, idGenerator: IdGeneratorService, certify: CertifyRepository);
    execute(input: CertifyIdentityProviderInput): Promise<CertifyIdentityProviderOutput>;
}
