/**
 * ExecuteSuspendIdentityProvider - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSuspendIdentityProvider Use Case
 *
 * DDD: Application use case for get Suspend.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SuspendIdentityProviderInput, SuspendIdentityProviderOutput } from "../dto/suspend.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { SuspendRepository } from "../ports/index.js";
import { NotFoundError, ValidationError } from "../errors/index.js";

export class ExecuteSuspendIdentityProvider {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly suspend: SuspendRepository
  ) {}

  async execute(input: SuspendIdentityProviderInput): Promise<SuspendIdentityProviderOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dirId();

    // All field names extracted from OpenAPI spec: reason, rulebookVersion
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).idpId) {
      throw new ValidationError("idpId is required");
    }
    const idpId = (input as any).idpId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.suspend.suspendIdentityProvider({ idpId: idpId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${idpId}`);
    }

    return entity as SuspendIdentityProviderOutput;
  }
}
