/**
 * ExecuteListMembershipDecisions - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
export class ExecuteListMembershipDecisions {
    context;
    idGenerator;
    membershipDecision;
    constructor(context, idGenerator, membershipDecision) {
        this.context = context;
        this.idGenerator = idGenerator;
        this.membershipDecision = membershipDecision;
    }
    async execute(input) {
        // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
        const correlationId = this.idGenerator.dirId();
        // All field names extracted from OpenAPI spec: none
        // List entities via repository
        const result = await this.membershipDecision.listMembershipDecisions({ ...input, orgId: this.context.getOrgId(), correlationId });
        return result;
    }
}
