/**
 * ExecuteCertifyRelyingParty - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * ExecuteCertifyRelyingParty Use Case
 *
 * DDD: Application use case for get Certify.
 * Orchestrates the business flow using ports (interfaces).
 */
import type { CertifyRelyingPartyInput, CertifyRelyingPartyOutput } from "../dto/certify.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { CertifyRepository } from "../ports/index.js";
export declare class ExecuteCertifyRelyingParty {
    private readonly context;
    private readonly idGenerator;
    private readonly certify;
    constructor(context: ExecutionContextService, idGenerator: IdGeneratorService, certify: CertifyRepository);
    execute(input: CertifyRelyingPartyInput): Promise<CertifyRelyingPartyOutput>;
}
