/**
 * ExecuteRegisterIdentityProvider - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteRegisterIdentityProvider {
    context;
    idGenerator;
    identityProvider;
    constructor(context, idGenerator, identityProvider) {
        this.context = context;
        this.idGenerator = idGenerator;
        this.identityProvider = identityProvider;
    }
    async execute(input) {
        // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
        const correlationId = this.idGenerator.dirId();
        // All field names extracted from OpenAPI spec: jurisdictions, legalName, maxAssuranceLevel
        // Validate input
        if (!input) {
            throw new ValidationError("Input is required");
        }
        if (!input.maxAssuranceLevel) {
            throw new ValidationError("maxAssuranceLevel is required");
        }
        if (!input.legalName) {
            throw new ValidationError("legalName is required");
        } // Check policy
        if (!CanCreate.allow({}, "")) {
            throw new PermissionDeniedError("Operation not allowed");
        }
        // Generate entity ID in services layer using IdGeneratorService (directory domain)
        const entityId = this.idGenerator.dirId();
        // Create entity via repository (pass ID and correlation ID for response meta)
        const entity = await this.identityProvider.registerIdentityProvider({ ...input, id: entityId, createdByActorId: input.createdByActorId ?? this.context.getUserId(), createdByActorType: input.createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId });
        return entity;
    }
}
