/**
 * ExecuteListRelyingParties - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * ExecuteListRelyingParties Use Case
 *
 * DDD: Application use case for list RelyingParty.
 * Orchestrates the business flow using ports (interfaces).
 */
import type { ListRelyingPartiesInput, ListRelyingPartiesOutput } from "../dto/relying-party.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { RelyingPartyRepository } from "../ports/index.js";
export declare class ExecuteListRelyingParties {
    private readonly context;
    private readonly idGenerator;
    private readonly relyingParty;
    constructor(context: ExecutionContextService, idGenerator: IdGeneratorService, relyingParty: RelyingPartyRepository);
    execute(input: ListRelyingPartiesInput): Promise<ListRelyingPartiesOutput>;
}
