/**
 * ExecuteListRelyingParties - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListRelyingParties Use Case
 *
 * DDD: Application use case for list RelyingParty.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListRelyingPartiesInput, ListRelyingPartiesOutput } from "../dto/relying-party.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { RelyingPartyRepository } from "../ports/index.js";

export class ExecuteListRelyingParties {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly relyingParty: RelyingPartyRepository
  ) {}

  async execute(input: ListRelyingPartiesInput): Promise<ListRelyingPartiesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dirId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.relyingParty.listRelyingParties({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListRelyingPartiesOutput;
  }
}
