/**
 * AttestationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * AttestationRepository Port
 *
 * DDD: Application port for attestationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */
import type { GetAttestationInput, GetAttestationOutput, ListAttestationsInput, ListAttestationsOutput, RequestAttestationInput, RequestAttestationOutput } from "../dto/attestation.dto";
export interface AttestationRepository {
    listAttestations(input: ListAttestationsInput): Promise<ListAttestationsOutput>;
    requestAttestation(input: RequestAttestationInput): Promise<RequestAttestationOutput>;
    getAttestation(input: GetAttestationInput): Promise<GetAttestationOutput>;
}
export type { GetAttestationInput, GetAttestationOutput, ListAttestationsInput, ListAttestationsOutput, RequestAttestationInput, RequestAttestationOutput } from "../dto/attestation.dto";
