/**
 * Routes for Invoice
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { generateSettlementInvoice, getSettlementInvoice, listSettlementInvoices } from "../handlers/invoice.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function invoiceRoutes(fastify: FastifyInstance) {
  // POST /v1/settlement/invoices (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/settlement/invoices",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSettlementDependenciesForRequest();
        await generateSettlementInvoice(request, reply, deps);
      });
    }
  );


  // GET /v1/settlement/invoices (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/settlement/invoices",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSettlementDependenciesForRequest();
        await listSettlementInvoices(request, reply, deps);
      });
    }
  );


  // GET /v1/settlement/invoices/{invoiceId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/settlement/invoices/:invoiceId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { invoiceId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSettlementDependenciesForRequest();
        await getSettlementInvoice(request, reply, deps);
      });
    }
  );


}
