/**
 * ExecuteRefreshScreeningSnapshot - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: screening
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
export class ExecuteRefreshScreeningSnapshot {
    context;
    idGenerator;
    snapshot;
    constructor(context, idGenerator, snapshot) {
        this.context = context;
        this.idGenerator = idGenerator;
        this.snapshot = snapshot;
    }
    async execute(input) {
        // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
        const correlationId = this.idGenerator.scrId();
        // Delegate to repository port
        const result = await this.snapshot.refreshScreeningSnapshot({ ...input, orgId: this.context.getOrgId(), correlationId });
        return result;
    }
}
