/**
 * ExecuteListScreeningSnapshots - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: screening
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListScreeningSnapshots Use Case
 *
 * DDD: Application use case for list Snapshot.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListScreeningSnapshotsInput, ListScreeningSnapshotsOutput } from "../dto/snapshot.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { SnapshotRepository } from "../ports/index.js";

export class ExecuteListScreeningSnapshots {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly snapshot: SnapshotRepository
  ) {}

  async execute(input: ListScreeningSnapshotsInput): Promise<ListScreeningSnapshotsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.scrId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.snapshot.listScreeningSnapshots({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListScreeningSnapshotsOutput;
  }
}
