/**
 * ExecuteRefreshScreeningSnapshot - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: screening
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRefreshScreeningSnapshot Use Case
 *
 * DDD: Application use case for update Snapshot.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RefreshScreeningSnapshotInput, RefreshScreeningSnapshotOutput } from "../dto/snapshot.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { SnapshotRepository } from "../ports/index.js";

export class ExecuteRefreshScreeningSnapshot {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly snapshot: SnapshotRepository
  ) {}

  async execute(input: RefreshScreeningSnapshotInput): Promise<RefreshScreeningSnapshotOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.scrId();

    // Delegate to repository port
    const result = await this.snapshot.refreshScreeningSnapshot({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    return result as RefreshScreeningSnapshotOutput;
  }
}
