/**
 * ExecuteInvalidateStaleScreeningDependents - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: screening
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { NotFoundError, ValidationError } from "../errors";
export class ExecuteInvalidateStaleScreeningDependents {
    context;
    idGenerator;
    invalidateDependent;
    constructor(context, idGenerator, invalidateDependent) {
        this.context = context;
        this.idGenerator = idGenerator;
        this.invalidateDependent = invalidateDependent;
    }
    async execute(input) {
        // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
        const correlationId = this.idGenerator.scrId();
        // All field names extracted from OpenAPI spec: none
        // Validate input
        if (!input) {
            throw new ValidationError("Input is required");
        }
        if (!input.snapshotId) {
            throw new ValidationError("snapshotId is required");
        }
        const snapshotId = input.snapshotId;
        // Load entity via repository (pass correlation ID for response meta)
        const entity = await this.invalidateDependent.invalidateStaleScreeningDependents({ snapshotId: snapshotId, orgId: this.context.getOrgId(), correlationId });
        if (!entity) {
            throw new NotFoundError(`Entity not found: ${snapshotId}`);
        }
        return entity;
    }
}
