/**
 * UnlinkLegalEntity handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { unlinkLegalEntity } from "@kyvora/api-server/domains/subjects/handlers";
import type { SubjectsDDDDependencies } from "@kyvora/api-server/domains/subjects";
import { createLegalEntityLink as createLegalEntityLinkEntity } from "@kyvora/factories/subjects";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@kyvora/tests/shared";
import { SUBJECTS_USE_CASES } from "../__factories__/use-cases.js";

describe("UnlinkLegalEntity", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SubjectsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SubjectsDDDDependencies>(
      SUBJECTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 204 on successful deletion", async () => {
    const entity = createLegalEntityLinkEntity({ orgId });
    mockRequest.params = { linkId: entity.id };
    
    vi.spyOn(mockDeps.executeUnlinkLegalEntity, "execute").mockResolvedValue(undefined);

    await unlinkLegalEntity(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeUnlinkLegalEntity.execute).toHaveBeenCalledWith(expect.objectContaining({ linkId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(204);
  });

});
