/**
 * ConsentRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { ConsentRepositoryDdb } from "./consent-repository.ddb.js";
/**
 * ConsentRepositoryAdapter
 *
 * Implements ConsentRepository port for infrastructure layer.
 */
export class ConsentRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new ConsentRepositoryDdb(this.dynamoClient);
    }
    async listConsentGrants(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.listConsentGrants(input);
    }
    async createConsentGrant(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.createConsentGrant(input);
    }
    async getConsentGrant(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.getConsentGrant(input);
    }
}
