/**
 * ConsentRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConsentRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ConsentRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ConsentRepository,
} from "@kyvora/services/consents";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ConsentRepositoryDdb } from "./consent-repository.ddb.js";

/**
 * ConsentRepositoryAdapter
 *
 * Implements ConsentRepository port for infrastructure layer.
 */
export class ConsentRepositoryAdapter implements ConsentRepository {
  private readonly ddb: ConsentRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ConsentRepositoryDdb(this.dynamoClient);
  }

  async listConsentGrants(input: Parameters<ConsentRepository['listConsentGrants']>[0]): Promise<Awaited<ReturnType<ConsentRepository['listConsentGrants']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listConsentGrants(input);
  }

  async createConsentGrant(input: Parameters<ConsentRepository['createConsentGrant']>[0]): Promise<Awaited<ReturnType<ConsentRepository['createConsentGrant']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createConsentGrant(input);
  }

  async getConsentGrant(input: Parameters<ConsentRepository['getConsentGrant']>[0]): Promise<Awaited<ReturnType<ConsentRepository['getConsentGrant']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getConsentGrant(input);
  }
}
