/**
 * RevokeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { RevokeRepositoryDdb } from "./revoke-repository.ddb.js";
/**
 * RevokeRepositoryAdapter
 *
 * Implements RevokeRepository port for infrastructure layer.
 */
export class RevokeRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new RevokeRepositoryDdb(this.dynamoClient);
    }
    async revokeConsentGrant(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.revokeConsentGrant(input);
    }
}
