/**
 * System Routes - Health check and routes listing
 *
 * AUTO-GENERATED by codegen (api_server_system_routes). Do not edit by hand.
 * Domains and routeExamples are derived from discovered api-server domains and
 * each domain's OpenAPI bundled spec.
 */

import type { FastifyInstance } from "fastify";
import {
  getCoreTableName,
  getBaseTableName,
  getAnalyticsTableName,
} from "@kyvora/adapters";
import { getRegisteredRoutes } from "./route-registry.js";

/**
 * Register system routes (health check, routes listing)
 */
export function registerSystemRoutes(fastify: FastifyInstance): void {
  // Health check (public - no auth required)
  fastify.get("/health", { config: { scope: "public" } }, async () => {
    try {
      const coreTable = getCoreTableName();
      const baseTable = getBaseTableName();
      const analyticsTable = getAnalyticsTableName();
      return {
        status: "ok",
        service: "kyvora-api",
        database: "dynamodb",
        tables: {
          core: coreTable,
          base: baseTable,
          analytics: analyticsTable,
        },
      };
    } catch (error: unknown) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      fastify.log.warn({ error: errorMessage }, "Health check: DynamoDB not configured (sandbox ok)");
      return {
        status: "ok",
        service: "kyvora-api",
        database: "sandbox",
        warning: errorMessage,
      };
    }
  });

  // Routes listing endpoint (public)
  fastify.get("/routes", { config: { scope: "public" } }, async () => {
    const domains = [
      "attestations", "audit", "consents", "directory", "disputes", "identity", "screening", "settlement", "subjects"
    ];

    const routeExamples: Record<
      string,
      Array<{ method: string; path: string; description?: string }>
    > = {
      attestations: [{ method: "GET", path: "/v1/attestations" }, { method: "POST", path: "/v1/attestations" }, { method: "GET", path: "/v1/attestations/:attestationId" }, { method: "POST", path: "/v1/attestations/:attestationId/issue" }, { method: "POST", path: "/v1/attestations/:attestationId/refuse" }, { method: "POST", path: "/v1/attestations/:attestationId/revoke" }, { method: "POST", path: "/v1/attestations/:attestationId/document-recollect-exception" }],
      audit: [{ method: "GET", path: "/v1/audit/evidence-packs" }, { method: "POST", path: "/v1/audit/evidence-packs" }, { method: "GET", path: "/v1/audit/evidence-packs/:packId" }, { method: "GET", path: "/v1/audit/evidence-packs/:packId/download" }],
      consents: [{ method: "GET", path: "/v1/consents" }, { method: "POST", path: "/v1/consents" }, { method: "GET", path: "/v1/consents/:consentId" }, { method: "POST", path: "/v1/consents/:consentId/revoke" }],
      directory: [{ method: "GET", path: "/v1/directory/identity-providers" }, { method: "POST", path: "/v1/directory/identity-providers" }, { method: "GET", path: "/v1/directory/identity-providers/:idpId" }, { method: "POST", path: "/v1/directory/identity-providers/:idpId/certify" }, { method: "POST", path: "/v1/directory/identity-providers/:idpId/suspend" }, { method: "GET", path: "/v1/directory/relying-parties" }, { method: "POST", path: "/v1/directory/relying-parties" }, { method: "GET", path: "/v1/directory/relying-parties/:rpId" }, { method: "POST", path: "/v1/directory/relying-parties/:rpId/certify" }, { method: "POST", path: "/v1/directory/relying-parties/:rpId/suspend" }, { method: "GET", path: "/v1/directory/membership-decisions" }],
      disputes: [{ method: "GET", path: "/v1/disputes" }, { method: "POST", path: "/v1/disputes" }, { method: "GET", path: "/v1/disputes/:disputeId" }, { method: "POST", path: "/v1/disputes/:disputeId/resolve" }],
      identity: [{ method: "GET", path: "/v0/tenants/me/api-keys" }, { method: "POST", path: "/v0/tenants/me/api-keys" }, { method: "GET", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "DELETE", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "GET", path: "/v0/tenants/me/users" }, { method: "POST", path: "/v0/tenants/me/users" }, { method: "GET", path: "/v0/tenants/me/users/:userId" }, { method: "PATCH", path: "/v0/tenants/me/users/:userId" }, { method: "POST", path: "/v0/tenants/me/users/:userId/disable" }, { method: "POST", path: "/v0/tenants/me/users/:userId/enable" }, { method: "POST", path: "/v0/auth/login" }, { method: "GET", path: "/v0/auth/me" }, { method: "PATCH", path: "/v0/auth/me" }, { method: "POST", path: "/v0/auth/refresh" }, { method: "POST", path: "/v0/auth/logout" }],
      screening: [{ method: "GET", path: "/v1/screening/snapshots" }, { method: "POST", path: "/v1/screening/snapshots" }, { method: "GET", path: "/v1/screening/snapshots/:snapshotId" }, { method: "POST", path: "/v1/screening/snapshots/:snapshotId/invalidate-dependents" }],
      settlement: [{ method: "GET", path: "/v1/settlement/fee-schedules" }, { method: "POST", path: "/v1/settlement/fee-schedules" }, { method: "GET", path: "/v1/settlement/fee-schedules/:scheduleId" }, { method: "GET", path: "/v1/settlement/invoices" }, { method: "POST", path: "/v1/settlement/invoices" }, { method: "GET", path: "/v1/settlement/invoices/:invoiceId" }, { method: "POST", path: "/v1/settlement/invoices/:invoiceId/export" }],
      subjects: [{ method: "GET", path: "/v1/subjects" }, { method: "POST", path: "/v1/subjects" }, { method: "GET", path: "/v1/subjects/:subjectId" }, { method: "PATCH", path: "/v1/subjects/:subjectId" }, { method: "GET", path: "/v1/subjects/:subjectId/attributes" }, { method: "POST", path: "/v1/subjects/:subjectId/attributes" }, { method: "GET", path: "/v1/subjects/:subjectId/legal-entity-links" }, { method: "POST", path: "/v1/subjects/:subjectId/legal-entity-links" }, { method: "DELETE", path: "/v1/legal-entity-links/:linkId" }, { method: "GET", path: "/v1/refresh-cycles" }, { method: "POST", path: "/v1/refresh-cycles" }, { method: "POST", path: "/v1/refresh-cycles/:cycleId/complete" }],
    };

    return {
      baseUrl: "http://localhost:4000",
      routePattern: "/orgs/:orgId/{domain}/{resource}",
      authentication:
        "All routes (except /health and /routes) require JWT token in Authorization header",
      domains: domains.sort(),
      routeExamples,
      systemRoutes: [
        { method: "GET", path: "/health", description: "Health check endpoint" },
        { method: "GET", path: "/routes", description: "List available routes" },
      ],
      note: "Replace :orgId with actual organization ID. All domain routes require authentication.",
    };
  });

  // Full route list for API tester page (public)
  fastify.get("/routes/full", { config: { scope: "public" } }, async () => {
    const routes = getRegisteredRoutes();
    const byDomain: Record<
      string,
      Array<{ method: string; path: string }>
    > = {};
    const system: Array<{ method: string; path: string }> = [];
    for (const r of routes) {
      const m = r.path.match(/^\/orgs\/:orgId\/([^/]+)/);
      if (m) {
        const domain = m[1];
        if (!byDomain[domain]) byDomain[domain] = [];
        byDomain[domain].push(r);
      } else {
        system.push(r);
      }
    }
    return {
      baseUrl: "http://localhost:4000",
      total: routes.length,
      system,
      byDomain: Object.keys(byDomain)
        .sort()
        .reduce(
          (acc, k) => ({ ...acc, [k]: byDomain[k] }),
          {} as Record<string, Array<{ method: string; path: string }>>,
        ),
    };
  });
}
