/**
 * ApiKeyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { ApiKeyRepositoryDdb } from "./api-key-repository.ddb.js";
/**
 * ApiKeyRepositoryAdapter
 *
 * Implements ApiKeyRepository port for infrastructure layer.
 */
export class ApiKeyRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new ApiKeyRepositoryDdb(this.dynamoClient);
    }
    async listTenantApiKeys(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.listTenantApiKeys(input);
    }
    async createTenantApiKey(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.createTenantApiKey(input);
    }
    async getTenantApiKey(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.getTenantApiKey(input);
    }
    async revokeTenantApiKey(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.revokeTenantApiKey(input);
    }
}
