/**
 * ApiKeyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * ApiKeyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ApiKeyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */
import type { ApiKeyRepository } from "@kyvora/services/identity";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
/**
 * ApiKeyRepositoryAdapter
 *
 * Implements ApiKeyRepository port for infrastructure layer.
 */
export declare class ApiKeyRepositoryAdapter implements ApiKeyRepository {
    private readonly dynamoClient;
    private readonly ddb;
    constructor(dynamoClient: AdapterDynamoDBClient);
    listTenantApiKeys(input: Parameters<ApiKeyRepository['listTenantApiKeys']>[0]): Promise<Awaited<ReturnType<ApiKeyRepository['listTenantApiKeys']>>>;
    createTenantApiKey(input: Parameters<ApiKeyRepository['createTenantApiKey']>[0]): Promise<Awaited<ReturnType<ApiKeyRepository['createTenantApiKey']>>>;
    getTenantApiKey(input: Parameters<ApiKeyRepository['getTenantApiKey']>[0]): Promise<Awaited<ReturnType<ApiKeyRepository['getTenantApiKey']>>>;
    revokeTenantApiKey(input: Parameters<ApiKeyRepository['revokeTenantApiKey']>[0]): Promise<Awaited<ReturnType<ApiKeyRepository['revokeTenantApiKey']>>>;
}
