/**
 * DisableRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * DisableRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DisableRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */
import type { DisableRepository } from "@kyvora/services/identity";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
/**
 * DisableRepositoryAdapter
 *
 * Implements DisableRepository port for infrastructure layer.
 */
export declare class DisableRepositoryAdapter implements DisableRepository {
    private readonly dynamoClient;
    private readonly ddb;
    constructor(dynamoClient: AdapterDynamoDBClient);
    disableTenantUser(input: Parameters<DisableRepository['disableTenantUser']>[0]): Promise<Awaited<ReturnType<DisableRepository['disableTenantUser']>>>;
}
