/**
 * EnableRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { EnableRepositoryDdb } from "./enable-repository.ddb.js";
/**
 * EnableRepositoryAdapter
 *
 * Implements EnableRepository port for infrastructure layer.
 */
export class EnableRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new EnableRepositoryDdb(this.dynamoClient);
    }
    async enableTenantUser(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.enableTenantUser(input);
    }
}
