/**
 * EnableRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * EnableRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements EnableRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */
import type { EnableRepository } from "@kyvora/services/identity";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
/**
 * EnableRepositoryAdapter
 *
 * Implements EnableRepository port for infrastructure layer.
 */
export declare class EnableRepositoryAdapter implements EnableRepository {
    private readonly dynamoClient;
    private readonly ddb;
    constructor(dynamoClient: AdapterDynamoDBClient);
    enableTenantUser(input: Parameters<EnableRepository['enableTenantUser']>[0]): Promise<Awaited<ReturnType<EnableRepository['enableTenantUser']>>>;
}
