/**
 * UserRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { UserRepositoryDdb } from "./user-repository.ddb.js";
/**
 * UserRepositoryAdapter
 *
 * Implements UserRepository port for infrastructure layer.
 */
export class UserRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new UserRepositoryDdb(this.dynamoClient);
    }
    async listTenantUsers(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.listTenantUsers(input);
    }
    async createTenantUser(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.createTenantUser(input);
    }
    async getTenantUser(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.getTenantUser(input);
    }
    async updateTenantUser(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.updateTenantUser(input);
    }
}
