/**
 * UserRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * UserRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements UserRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */
import type { UserRepository } from "@kyvora/services/identity";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
/**
 * UserRepositoryAdapter
 *
 * Implements UserRepository port for infrastructure layer.
 */
export declare class UserRepositoryAdapter implements UserRepository {
    private readonly dynamoClient;
    private readonly ddb;
    constructor(dynamoClient: AdapterDynamoDBClient);
    listTenantUsers(input: Parameters<UserRepository['listTenantUsers']>[0]): Promise<Awaited<ReturnType<UserRepository['listTenantUsers']>>>;
    createTenantUser(input: Parameters<UserRepository['createTenantUser']>[0]): Promise<Awaited<ReturnType<UserRepository['createTenantUser']>>>;
    getTenantUser(input: Parameters<UserRepository['getTenantUser']>[0]): Promise<Awaited<ReturnType<UserRepository['getTenantUser']>>>;
    updateTenantUser(input: Parameters<UserRepository['updateTenantUser']>[0]): Promise<Awaited<ReturnType<UserRepository['updateTenantUser']>>>;
}
