/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./create-subject.handler.test.js";
export * from "./get-subject.handler.test.js";
export * from "./list-subjects.handler.test.js";
export * from "./update-subject.handler.test.js";
