/**
 * ExecuteRegisterSubjectAttribute - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * ExecuteRegisterSubjectAttribute Use Case
 *
 * DDD: Application use case for create Attribute.
 * Orchestrates the business flow using ports (interfaces).
 */
import type { RegisterSubjectAttributeInput, RegisterSubjectAttributeOutput } from "../dto/attribute.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { AttributeRepository } from "../ports/index.js";
export declare class ExecuteRegisterSubjectAttribute {
    private readonly context;
    private readonly idGenerator;
    private readonly attribute;
    constructor(context: ExecutionContextService, idGenerator: IdGeneratorService, attribute: AttributeRepository);
    execute(input: RegisterSubjectAttributeInput): Promise<RegisterSubjectAttributeOutput>;
}
