/**
 * ExecuteListRefreshCycles - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * ExecuteListRefreshCycles Use Case
 *
 * DDD: Application use case for list RefreshCycle.
 * Orchestrates the business flow using ports (interfaces).
 */
import type { ListRefreshCyclesInput, ListRefreshCyclesOutput } from "../dto/refresh-cycle.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { RefreshCycleRepository } from "../ports/index.js";
export declare class ExecuteListRefreshCycles {
    private readonly context;
    private readonly idGenerator;
    private readonly refreshCycle;
    constructor(context: ExecutionContextService, idGenerator: IdGeneratorService, refreshCycle: RefreshCycleRepository);
    execute(input: ListRefreshCyclesInput): Promise<ListRefreshCyclesOutput>;
}
