/**
 * ExecuteCreateSubject - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateSubject Use Case
 *
 * DDD: Application use case for create Subject.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateSubjectInput, CreateSubjectOutput } from "../dto/subject.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { SubjectRepository } from "../ports/index.js";
import { PermissionDeniedError, ValidationError } from "../errors/index.js";
import { CanCreate } from "../policies/can-create.policy.js";
export class ExecuteCreateSubject {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly subject: SubjectRepository
  ) {}

  async execute(input: CreateSubjectInput): Promise<CreateSubjectOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.subId();

    // All field names extracted from OpenAPI spec: displayRef, inclusionTier, subjectType
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.subjectType) {
      throw new ValidationError("subjectType is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (subjects domain)
    const entityId = this.idGenerator.subId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.subject.createSubject({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateSubjectOutput;
  }
}
