/**
 * ExecuteCreateSubject - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateSubject {
    context;
    idGenerator;
    subject;
    constructor(context, idGenerator, subject) {
        this.context = context;
        this.idGenerator = idGenerator;
        this.subject = subject;
    }
    async execute(input) {
        // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
        const correlationId = this.idGenerator.subId();
        // All field names extracted from OpenAPI spec: displayRef, inclusionTier, subjectType
        // Validate input
        if (!input) {
            throw new ValidationError("Input is required");
        }
        if (!input.subjectType) {
            throw new ValidationError("subjectType is required");
        } // Check policy
        if (!CanCreate.allow({}, "")) {
            throw new PermissionDeniedError("Operation not allowed");
        }
        // Generate entity ID in services layer using IdGeneratorService (subjects domain)
        const entityId = this.idGenerator.subId();
        // Create entity via repository (pass ID and correlation ID for response meta)
        const entity = await this.subject.createSubject({ ...input, id: entityId, createdByActorId: input.createdByActorId ?? this.context.getUserId(), createdByActorType: input.createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId });
        return entity;
    }
}
