/**
 * ExecuteListLegalEntityLinks - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
export class ExecuteListLegalEntityLinks {
    context;
    idGenerator;
    legalEntityLink;
    constructor(context, idGenerator, legalEntityLink) {
        this.context = context;
        this.idGenerator = idGenerator;
        this.legalEntityLink = legalEntityLink;
    }
    async execute(input) {
        // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
        const correlationId = this.idGenerator.subId();
        // All field names extracted from OpenAPI spec: none
        // List entities via repository
        const result = await this.legalEntityLink.listLegalEntityLinks({ ...input, orgId: this.context.getOrgId(), correlationId });
        return result;
    }
}
