/**
 * ExecuteUpdateSubject - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateSubject Use Case
 *
 * DDD: Application use case for update Subject.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateSubjectInput, UpdateSubjectOutput } from "../dto/subject.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { SubjectRepository } from "../ports/index.js";
import { NotFoundError, PermissionDeniedError, ValidationError } from "../errors/index.js";
import { CanUpdate } from "../policies/can-update.policy.js";
export class ExecuteUpdateSubject {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly subject: SubjectRepository
  ) {}

  async execute(input: UpdateSubjectInput): Promise<UpdateSubjectOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.subId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).subjectId) {
      throw new ValidationError("subjectId is required");
    }
    const subjectId = (input as any).subjectId;

    // Load existing entity
    const existing = await this.subject.getSubject({ subjectId: subjectId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!existing) {
      throw new NotFoundError(`Entity not found: ${subjectId}`);
    }
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.subject.updateSubject({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateSubjectOutput;
  }
}
