/**
 * ExecuteUnlinkLegalEntity - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUnlinkLegalEntity Use Case
 *
 * DDD: Application use case for get LegalEntityLink.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UnlinkLegalEntityInput, UnlinkLegalEntityOutput } from "../dto/legal-entity-link.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { LegalEntityLinkRepository } from "../ports/index.js";
import { NotFoundError, ValidationError } from "../errors/index.js";

export class ExecuteUnlinkLegalEntity {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly legalEntityLink: LegalEntityLinkRepository
  ) {}

  async execute(input: UnlinkLegalEntityInput): Promise<UnlinkLegalEntityOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.subId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).linkId) {
      throw new ValidationError("linkId is required");
    }
    const linkId = (input as any).linkId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.legalEntityLink.unlinkLegalEntity({ linkId: linkId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${linkId}`);
    }

    return entity as UnlinkLegalEntityOutput;
  }
}
