/**
 * ExecuteListLegalEntityLinks - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * ExecuteListLegalEntityLinks Use Case
 *
 * DDD: Application use case for list LegalEntityLink.
 * Orchestrates the business flow using ports (interfaces).
 */
import type { ListLegalEntityLinksInput, ListLegalEntityLinksOutput } from "../dto/legal-entity-link.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { LegalEntityLinkRepository } from "../ports/index.js";
export declare class ExecuteListLegalEntityLinks {
    private readonly context;
    private readonly idGenerator;
    private readonly legalEntityLink;
    constructor(context: ExecutionContextService, idGenerator: IdGeneratorService, legalEntityLink: LegalEntityLinkRepository);
    execute(input: ListLegalEntityLinksInput): Promise<ListLegalEntityLinksOutput>;
}
