/**
 * ExecuteListSubjects - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListSubjects Use Case
 *
 * DDD: Application use case for list Subject.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListSubjectsInput, ListSubjectsOutput } from "../dto/subject.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { SubjectRepository } from "../ports/index.js";

export class ExecuteListSubjects {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly subject: SubjectRepository
  ) {}

  async execute(input: ListSubjectsInput): Promise<ListSubjectsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.subId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.subject.listSubjects({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListSubjectsOutput;
  }
}
