/**
 * ExecuteCompleteRefreshCycle - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * ExecuteCompleteRefreshCycle Use Case
 *
 * DDD: Application use case for create Complete.
 * Orchestrates the business flow using ports (interfaces).
 */
import type { CompleteRefreshCycleInput, CompleteRefreshCycleOutput } from "../dto/complete.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { CompleteRepository } from "../ports/index.js";
export declare class ExecuteCompleteRefreshCycle {
    private readonly context;
    private readonly idGenerator;
    private readonly complete;
    constructor(context: ExecutionContextService, idGenerator: IdGeneratorService, complete: CompleteRepository);
    execute(input: CompleteRefreshCycleInput): Promise<CompleteRefreshCycleOutput>;
}
