/**
 * ExecuteListTenantUsers - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
export class ExecuteListTenantUsers {
    context;
    idGenerator;
    user;
    constructor(context, idGenerator, user) {
        this.context = context;
        this.idGenerator = idGenerator;
        this.user = user;
    }
    async execute(input) {
        // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
        const correlationId = this.idGenerator.idnId();
        // All field names extracted from OpenAPI spec: none
        // List entities via repository
        const result = await this.user.listTenantUsers({ ...input, orgId: this.context.getOrgId(), correlationId });
        return result;
    }
}
