/**
 * ExecuteOperatorLogout - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * ExecuteOperatorLogout Use Case
 *
 * DDD: Application use case for get Logout.
 * Orchestrates the business flow using ports (interfaces).
 */
import type { OperatorLogoutInput, OperatorLogoutOutput } from "../dto/logout.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { LogoutRepository } from "../ports/index.js";
export declare class ExecuteOperatorLogout {
    private readonly context;
    private readonly idGenerator;
    private readonly logout;
    constructor(context: ExecutionContextService, idGenerator: IdGeneratorService, logout: LogoutRepository);
    execute(input: OperatorLogoutInput): Promise<OperatorLogoutOutput>;
}
