/**
 * ExecuteListTenantApiKeys - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * ExecuteListTenantApiKeys Use Case
 *
 * DDD: Application use case for list ApiKey.
 * Orchestrates the business flow using ports (interfaces).
 */
import type { ListTenantApiKeysInput, ListTenantApiKeysOutput } from "../dto/api-key.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { ApiKeyRepository } from "../ports/index.js";
export declare class ExecuteListTenantApiKeys {
    private readonly context;
    private readonly idGenerator;
    private readonly apiKey;
    constructor(context: ExecutionContextService, idGenerator: IdGeneratorService, apiKey: ApiKeyRepository);
    execute(input: ListTenantApiKeysInput): Promise<ListTenantApiKeysOutput>;
}
