/**
 * ExecuteUpdateTenantUser - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * ExecuteUpdateTenantUser Use Case
 *
 * DDD: Application use case for update User.
 * Orchestrates the business flow using ports (interfaces).
 */
import type { UpdateTenantUserInput, UpdateTenantUserOutput } from "../dto/user.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { UserRepository } from "../ports/index.js";
export declare class ExecuteUpdateTenantUser {
    private readonly context;
    private readonly idGenerator;
    private readonly user;
    constructor(context: ExecutionContextService, idGenerator: IdGeneratorService, user: UserRepository);
    execute(input: UpdateTenantUserInput): Promise<UpdateTenantUserOutput>;
}
