/**
 * ExecuteOperatorLogout - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { NotFoundError } from "../errors";
export class ExecuteOperatorLogout {
    context;
    idGenerator;
    logout;
    constructor(context, idGenerator, logout) {
        this.context = context;
        this.idGenerator = idGenerator;
        this.logout = logout;
    }
    async execute(input) {
        // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
        const correlationId = this.idGenerator.idnId();
        // All field names extracted from OpenAPI spec: none
        // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
        const entity = await this.logout.operatorLogout({ ...input, orgId: this.context.getOrgId(), correlationId });
        if (!entity) {
            throw new NotFoundError(`Entity not found`);
        }
        return entity;
    }
}
