/**
 * ExecuteCreateTenantApiKey - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateTenantApiKey {
    context;
    idGenerator;
    apiKey;
    constructor(context, idGenerator, apiKey) {
        this.context = context;
        this.idGenerator = idGenerator;
        this.apiKey = apiKey;
    }
    async execute(input) {
        // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
        const correlationId = this.idGenerator.idnId();
        // All field names extracted from OpenAPI spec: expiresAt, name, scopes
        // Validate input
        if (!input) {
            throw new ValidationError("Input is required");
        }
        if (!input.name) {
            throw new ValidationError("name is required");
        } // Check policy
        if (!CanCreate.allow({}, "")) {
            throw new PermissionDeniedError("Operation not allowed");
        }
        // Generate entity ID in services layer using IdGeneratorService (identity domain)
        const entityId = this.idGenerator.idnId();
        // Create entity via repository (pass ID and correlation ID for response meta)
        const entity = await this.apiKey.createTenantApiKey({ ...input, id: entityId, createdByActorId: input.createdByActorId ?? this.context.getUserId(), createdByActorType: input.createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId });
        return entity;
    }
}
