/**
 * ExecuteOperatorLogin - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * ExecuteOperatorLogin Use Case
 *
 * DDD: Application use case for get Login.
 * Orchestrates the business flow using ports (interfaces).
 */
import type { OperatorLoginInput, OperatorLoginOutput } from "../dto/login.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { LoginRepository } from "../ports/index.js";
export declare class ExecuteOperatorLogin {
    private readonly context;
    private readonly idGenerator;
    private readonly login;
    constructor(context: ExecutionContextService, idGenerator: IdGeneratorService, login: LoginRepository);
    execute(input: OperatorLoginInput): Promise<OperatorLoginOutput>;
}
