/**
 * ExecuteListDisputeCases - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
export class ExecuteListDisputeCases {
    context;
    idGenerator;
    dispute;
    constructor(context, idGenerator, dispute) {
        this.context = context;
        this.idGenerator = idGenerator;
        this.dispute = dispute;
    }
    async execute(input) {
        // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
        const correlationId = this.idGenerator.dspId();
        // All field names extracted from OpenAPI spec: none
        // List entities via repository
        const result = await this.dispute.listDisputeCases({ ...input, orgId: this.context.getOrgId(), correlationId });
        return result;
    }
}
