/**
 * ExecuteOpenDisputeCase - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteOpenDisputeCase Use Case
 *
 * DDD: Application use case for get Dispute.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { OpenDisputeCaseInput, OpenDisputeCaseOutput } from "../dto/dispute.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { DisputeRepository } from "../ports/index.js";
import { NotFoundError, ValidationError } from "../errors/index.js";

export class ExecuteOpenDisputeCase {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dispute: DisputeRepository
  ) {}

  async execute(input: OpenDisputeCaseInput): Promise<OpenDisputeCaseOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dspId();

    // All field names extracted from OpenAPI spec: attestationId, freezeDependentOnboardings, reason
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).attestationId) {
      throw new ValidationError("attestationId is required");
    }
    const attestationId = (input as any).attestationId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.dispute.openDisputeCase({ attestationId: attestationId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${attestationId}`);
    }

    return entity as OpenDisputeCaseOutput;
  }
}
