/**
 * ExecuteResolveDisputeCase - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteResolveDisputeCase Use Case
 *
 * DDD: Application use case for get Resolve.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ResolveDisputeCaseInput, ResolveDisputeCaseOutput } from "../dto/resolve.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { ResolveRepository } from "../ports/index.js";
import { NotFoundError, ValidationError } from "../errors/index.js";

export class ExecuteResolveDisputeCase {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly resolve: ResolveRepository
  ) {}

  async execute(input: ResolveDisputeCaseInput): Promise<ResolveDisputeCaseOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dspId();

    // All field names extracted from OpenAPI spec: resolutionNotes, revokeAttestation, status
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).disputeId) {
      throw new ValidationError("disputeId is required");
    }
    const disputeId = (input as any).disputeId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.resolve.resolveDisputeCase({ disputeId: disputeId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${disputeId}`);
    }

    return entity as ResolveDisputeCaseOutput;
  }
}
