/**
 * ExecuteResolveDisputeCase - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { NotFoundError, ValidationError } from "../errors";
export class ExecuteResolveDisputeCase {
    context;
    idGenerator;
    resolve;
    constructor(context, idGenerator, resolve) {
        this.context = context;
        this.idGenerator = idGenerator;
        this.resolve = resolve;
    }
    async execute(input) {
        // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
        const correlationId = this.idGenerator.dspId();
        // All field names extracted from OpenAPI spec: resolutionNotes, revokeAttestation, status
        // Validate input
        if (!input) {
            throw new ValidationError("Input is required");
        }
        if (!input.disputeId) {
            throw new ValidationError("disputeId is required");
        }
        const disputeId = input.disputeId;
        // Load entity via repository (pass correlation ID for response meta)
        const entity = await this.resolve.resolveDisputeCase({ disputeId: disputeId, orgId: this.context.getOrgId(), correlationId });
        if (!entity) {
            throw new NotFoundError(`Entity not found: ${disputeId}`);
        }
        return entity;
    }
}
