/**
 * DocumentRecollectException Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { DocumentRecollectExceptionEntity } from "@kyvora/core/attestations/models/index.js";
import { attestationsSchemas } from "@kyvora/core/attestations";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "att";

export function createDocumentRecollectException(overrides: Partial<DocumentRecollectExceptionEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    reason: overrides.reason ?? faker.lorem.word(),
    ...overrides,
  };

  return attestationsSchemas.DocumentRecollectException.parse(raw);
}

export function documentRecollectExceptionBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createDocumentRecollectException(overrides));
}
