/**
 * DisputeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { DisputeRepositoryDdb } from "./dispute-repository.ddb.js";
/**
 * DisputeRepositoryAdapter
 *
 * Implements DisputeRepository port for infrastructure layer.
 */
export class DisputeRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new DisputeRepositoryDdb(this.dynamoClient);
    }
    async listDisputeCases(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.listDisputeCases(input);
    }
    async openDisputeCase(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.openDisputeCase(input);
    }
    async getDisputeCase(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.getDisputeCase(input);
    }
}
