/**
 * DisputeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DisputeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DisputeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DisputeRepository,
} from "@kyvora/services/disputes";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DisputeRepositoryDdb } from "./dispute-repository.ddb.js";

/**
 * DisputeRepositoryAdapter
 *
 * Implements DisputeRepository port for infrastructure layer.
 */
export class DisputeRepositoryAdapter implements DisputeRepository {
  private readonly ddb: DisputeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DisputeRepositoryDdb(this.dynamoClient);
  }

  async listDisputeCases(input: Parameters<DisputeRepository['listDisputeCases']>[0]): Promise<Awaited<ReturnType<DisputeRepository['listDisputeCases']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDisputeCases(input);
  }

  async openDisputeCase(input: Parameters<DisputeRepository['openDisputeCase']>[0]): Promise<Awaited<ReturnType<DisputeRepository['openDisputeCase']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.openDisputeCase(input);
  }

  async getDisputeCase(input: Parameters<DisputeRepository['getDisputeCase']>[0]): Promise<Awaited<ReturnType<DisputeRepository['getDisputeCase']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getDisputeCase(input);
  }
}
