/**
 * ResolveRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { ResolveRepositoryDdb } from "./resolve-repository.ddb.js";
/**
 * ResolveRepositoryAdapter
 *
 * Implements ResolveRepository port for infrastructure layer.
 */
export class ResolveRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new ResolveRepositoryDdb(this.dynamoClient);
    }
    async resolveDisputeCase(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.resolveDisputeCase(input);
    }
}
