/**
 * Repository interface for DocumentRecollectException
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  DocumentRecollectExceptionEntity
} from "../models/document-recollect-exception.entity.js";
import type {
  DocumentRecollectException
} from "../types/index.js";
/**
 * DocumentRecollectExceptionRepository Interface
 */
export interface DocumentRecollectExceptionRepository extends CreateReadRepository<DocumentRecollectExceptionEntity, DocumentRecollectException, string, Record<string, never>> {

}
