/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Subjects Domain Use Cases
 * 
 * List of all use case names for the subjects domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const SUBJECTS_USE_CASES = [
  "executeCompleteRefreshCycle",
  "executeCreateLegalEntityLink",
  "executeCreateRefreshCycle",
  "executeCreateSubject",
  "executeGetSubject",
  "executeListLegalEntityLinks",
  "executeListRefreshCycles",
  "executeListSubjectAttributes",
  "executeListSubjects",
  "executeRegisterSubjectAttribute",
  "executeUnlinkLegalEntity",
  "executeUpdateSubject"
] as const;
