/**
 * GetIdentityProvider handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getIdentityProvider } from "@kyvora/api-server/domains/directory/handlers";
import type { DirectoryDDDDependencies } from "@kyvora/api-server/domains/directory";
import { createIdentityProvider as createIdentityProviderEntity } from "@kyvora/factories/directory";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@kyvora/tests/shared";
import { DIRECTORY_USE_CASES } from "../__factories__/use-cases.js";

describe("GetIdentityProvider", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DirectoryDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DirectoryDDDDependencies>(
      DIRECTORY_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createIdentityProviderEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetIdentityProvider, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { idpId: entity.id };

    await getIdentityProvider(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetIdentityProvider.execute).toHaveBeenCalledWith(expect.objectContaining({ idpId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { idpId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetIdentityProvider, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getIdentityProvider(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
