/**
 * Attestations DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Attestations Domain Module - Composition root
 *
 * DDD: Composition root for attestations domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AttestationRepositoryAdapter,
  DocumentRecollectExceptionRepositoryAdapter,
  IssueRepositoryAdapter,
  RefuseRepositoryAdapter,
  RevokeRepositoryAdapter,
} from "@kyvora/adapters/attestations";
import { getIdGeneratorService } from "@kyvora/adapters";
import type { AdapterDynamoDBClient } from "@kyvora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetAttestation,
  ExecuteIssueAttestation,
  ExecuteListAttestations,
  ExecuteRecordDocumentRecollectException,
  ExecuteRefuseAttestation,
  ExecuteRequestAttestation,
  ExecuteRevokeAttestation,
} from "@kyvora/services/attestations/usecases";
// Ports (interfaces)
import type {
  AttestationRepository,
  DocumentRecollectExceptionRepository,
  IssueRepository,
  RefuseRepository,
  RevokeRepository,
} from "@kyvora/services/attestations/ports";

export interface AttestationsDomainModule {
  repos: {
    attestations: AttestationRepository;
    documentRecollectExceptions: DocumentRecollectExceptionRepository;
    issues: IssueRepository;
    refuses: RefuseRepository;
    revokes: RevokeRepository;
  };
  useCases: {
    attestations: {
      get: ExecuteGetAttestation;
      list: ExecuteListAttestations;
    };
    documentRecollectExceptions: {
      get: ExecuteRecordDocumentRecollectException;
    };
    issues: {
      get: ExecuteIssueAttestation;
    };
    refuses: {
      get: ExecuteRefuseAttestation;
    };
    revokes: {
      get: ExecuteRevokeAttestation;
    };
  };
}

export function buildAttestationsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AttestationsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      attestations?: AttestationRepository;
      documentRecollectExceptions?: DocumentRecollectExceptionRepository;
      issues?: IssueRepository;
      refuses?: RefuseRepository;
      revokes?: RevokeRepository;
    } = {};

    obj.attestations = new AttestationRepositoryAdapter(dynamoClient);
    obj.documentRecollectExceptions = new DocumentRecollectExceptionRepositoryAdapter(dynamoClient);
    obj.issues = new IssueRepositoryAdapter(dynamoClient);
    obj.refuses = new RefuseRepositoryAdapter(dynamoClient);
    obj.revokes = new RevokeRepositoryAdapter(dynamoClient);
    return {
      attestations: obj.attestations!,
      documentRecollectExceptions: obj.documentRecollectExceptions!,
      issues: obj.issues!,
      refuses: obj.refuses!,
      revokes: obj.revokes!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    attestations: {
      get: new ExecuteGetAttestation(executionContext, idGenerator, repos.attestations),
      list: new ExecuteListAttestations(executionContext, idGenerator, repos.attestations),
    },
    documentRecollectExceptions: {
      get: new ExecuteRecordDocumentRecollectException(executionContext, idGenerator, repos.documentRecollectExceptions),
    },
    issues: {
      get: new ExecuteIssueAttestation(executionContext, idGenerator, repos.issues),
    },
    refuses: {
      get: new ExecuteRefuseAttestation(executionContext, idGenerator, repos.refuses),
    },
    revokes: {
      get: new ExecuteRevokeAttestation(executionContext, idGenerator, repos.revokes),
    },
  };
  return { repos, useCases: useCases as AttestationsDomainModule["useCases"] };
}
