/**
 * Routes for Consent
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createConsentGrant, getConsentGrant, listConsentGrants } from "../handlers/consent.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function consentRoutes(fastify: FastifyInstance) {
  // POST /v1/consents (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/consents",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getConsentsDependenciesForRequest();
        await createConsentGrant(request, reply, deps);
      });
    }
  );


  // GET /v1/consents (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/consents",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getConsentsDependenciesForRequest();
        await listConsentGrants(request, reply, deps);
      });
    }
  );


  // GET /v1/consents/{consentId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/consents/:consentId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { consentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getConsentsDependenciesForRequest();
        await getConsentGrant(request, reply, deps);
      });
    }
  );


}
