/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @kyvora/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@kyvora/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@kyvora/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@kyvora/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@kyvora/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@kyvora/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _attestations from "./attestations/index.js";
import * as _audit from "./audit/index.js";
import * as _consents from "./consents/index.js";
import * as _directory from "./directory/index.js";
import * as _disputes from "./disputes/index.js";
import * as _identity from "./identity/index.js";
import * as _screening from "./screening/index.js";
import * as _settlement from "./settlement/index.js";
import * as _subjects from "./subjects/index.js";

// Export as namespaces
export const _shared = __shared;
export const attestations = _attestations;
export const audit = _audit;
export const consents = _consents;
export const directory = _directory;
export const disputes = _disputes;
export const identity = _identity;
export const screening = _screening;
export const settlement = _settlement;
export const subjects = _subjects;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@kyvora/core"; activity.types.*
//   - Direct exports: import * from "@kyvora/core/activity/types/index.js"
//   - Direct exports: import * from "@kyvora/core/activity/repositories/index.js"
//   - Direct exports: import * from "@kyvora/core/activity/models/index.js"
//   - Direct exports: import * from "@kyvora/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Attestations Service
export { schemas as AttestationsSchemas } from "./attestations/schemas/attestations.schemas.js";

// Audit Service
export { schemas as AuditSchemas } from "./audit/schemas/audit.schemas.js";

// Consents Service
export { schemas as ConsentsSchemas } from "./consents/schemas/consents.schemas.js";

// Directory Service
export { schemas as DirectorySchemas } from "./directory/schemas/directory.schemas.js";

// Disputes Service
export { schemas as DisputesSchemas } from "./disputes/schemas/disputes.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Screening Service
export { schemas as ScreeningSchemas } from "./screening/schemas/screening.schemas.js";

// Settlement Service
export { schemas as SettlementSchemas } from "./settlement/schemas/settlement.schemas.js";

// Subjects Service
export { schemas as SubjectsSchemas } from "./subjects/schemas/subjects.schemas.js";

