/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * @kyvora/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@kyvora/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@kyvora/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@kyvora/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@kyvora/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@kyvora/core";
 */
import * as __shared from "./_shared/index.js";
import * as _attestations from "./attestations/index.js";
import * as _audit from "./audit/index.js";
import * as _consents from "./consents/index.js";
import * as _directory from "./directory/index.js";
import * as _disputes from "./disputes/index.js";
import * as _identity from "./identity/index.js";
import * as _screening from "./screening/index.js";
import * as _settlement from "./settlement/index.js";
import * as _subjects from "./subjects/index.js";
export declare const _shared: typeof __shared;
export declare const attestations: typeof _attestations;
export declare const audit: typeof _audit;
export declare const consents: typeof _consents;
export declare const directory: typeof _directory;
export declare const disputes: typeof _disputes;
export declare const identity: typeof _identity;
export declare const screening: typeof _screening;
export declare const settlement: typeof _settlement;
export declare const subjects: typeof _subjects;
export { DOMAIN_PREFIX_MAP, isValidDomainId, extractDomainFromId, } from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";
export { schemas as AttestationsSchemas } from "./attestations/schemas/attestations.schemas.js";
export { schemas as AuditSchemas } from "./audit/schemas/audit.schemas.js";
export { schemas as ConsentsSchemas } from "./consents/schemas/consents.schemas.js";
export { schemas as DirectorySchemas } from "./directory/schemas/directory.schemas.js";
export { schemas as DisputesSchemas } from "./disputes/schemas/disputes.schemas.js";
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";
export { schemas as ScreeningSchemas } from "./screening/schemas/screening.schemas.js";
export { schemas as SettlementSchemas } from "./settlement/schemas/settlement.schemas.js";
export { schemas as SubjectsSchemas } from "./subjects/schemas/subjects.schemas.js";
