/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */
export interface paths {
    "/v1/directory/identity-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List identity providers */
        get: operations["listIdentityProviders"];
        put?: never;
        /** Register an identity provider */
        post: operations["registerIdentityProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/directory/identity-providers/{idpId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get identity provider */
        get: operations["getIdentityProvider"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/directory/identity-providers/{idpId}/certify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Certify an IdP against published standards */
        post: operations["certifyIdentityProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/directory/identity-providers/{idpId}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suspend an IdP that breaches assurance standards */
        post: operations["suspendIdentityProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/directory/relying-parties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List relying parties */
        get: operations["listRelyingParties"];
        put?: never;
        /** Register a relying party */
        post: operations["registerRelyingParty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/directory/relying-parties/{rpId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get relying party */
        get: operations["getRelyingParty"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/directory/relying-parties/{rpId}/certify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Certify a relying party */
        post: operations["certifyRelyingParty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/directory/relying-parties/{rpId}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suspend a relying party */
        post: operations["suspendRelyingParty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/directory/membership-decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List certify/suspend decisions */
        get: operations["listMembershipDecisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        MemberStatus: "active" | "suspended" | "pending";
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        IdpId: string;
        /** @enum {string} */
        AssuranceLevel: "IAL1" | "IAL2" | "IAL3";
        IdentityProvider: {
            idpId: components["schemas"]["IdpId"];
            legalName: string;
            status: components["schemas"]["MemberStatus"];
            maxAssuranceLevel: components["schemas"]["AssuranceLevel"];
            jurisdictions?: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        IdentityProviderListResponse: {
            data: {
                items: components["schemas"]["IdentityProvider"][];
                nextCursor?: string;
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        IdentityProviderCreate: {
            legalName: string;
            maxAssuranceLevel: components["schemas"]["AssuranceLevel"];
            jurisdictions?: string[];
        };
        IdentityProviderResponse: {
            data: components["schemas"]["IdentityProvider"];
            meta?: components["schemas"]["ResponseMeta"];
        };
        MembershipDecisionCreate: {
            reason: string;
            rulebookVersion?: string;
        };
        RpId: string;
        RelyingParty: {
            rpId: components["schemas"]["RpId"];
            legalName: string;
            status: components["schemas"]["MemberStatus"];
            allowedPurposes: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        RelyingPartyListResponse: {
            data: {
                items: components["schemas"]["RelyingParty"][];
                nextCursor?: string;
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        RelyingPartyCreate: {
            legalName: string;
            allowedPurposes: string[];
        };
        RelyingPartyResponse: {
            data: components["schemas"]["RelyingParty"];
            meta?: components["schemas"]["ResponseMeta"];
        };
        DecisionId: string;
        MembershipDecision: {
            decisionId: components["schemas"]["DecisionId"];
            memberId: string;
            /** @enum {string} */
            memberType: "identityProvider" | "relyingParty";
            /** @enum {string} */
            action: "certify" | "suspend" | "admit";
            reason: string;
            rulebookVersion?: string;
            /** Format: date-time */
            decidedAt: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        MembershipDecisionListResponse: {
            data: {
                items: components["schemas"]["MembershipDecision"][];
                nextCursor?: string;
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
    };
    responses: {
        /** @description Error (RFC 7807 Problem Details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Idempotency key reuse with different body, or state conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Semantically invalid request (e.g. PACK_EMPTY) */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Opaque cursor from a previous list response. */
        Cursor: string;
        /** @description Page size. */
        Limit: number;
        /**
         * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
         *     Replay with the same key and body returns the original result; different
         *     body with the same key yields 409.
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listIdentityProviders: {
        parameters: {
            query?: {
                /** @description Opaque cursor from a previous list response. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
                status?: components["schemas"]["MemberStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description IdP page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityProviderListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    registerIdentityProvider: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentityProviderCreate"];
            };
        };
        responses: {
            /** @description IdP registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityProviderResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    getIdentityProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idpId: components["schemas"]["IdpId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description IdP */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityProviderResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    certifyIdentityProvider: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                idpId: components["schemas"]["IdpId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipDecisionCreate"];
            };
        };
        responses: {
            /** @description Certified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityProviderResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    suspendIdentityProvider: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                idpId: components["schemas"]["IdpId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipDecisionCreate"];
            };
        };
        responses: {
            /** @description Suspended */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityProviderResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    listRelyingParties: {
        parameters: {
            query?: {
                /** @description Opaque cursor from a previous list response. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
                status?: components["schemas"]["MemberStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RP page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelyingPartyListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    registerRelyingParty: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelyingPartyCreate"];
            };
        };
        responses: {
            /** @description RP registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelyingPartyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    getRelyingParty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rpId: components["schemas"]["RpId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RP */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelyingPartyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    certifyRelyingParty: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                rpId: components["schemas"]["RpId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipDecisionCreate"];
            };
        };
        responses: {
            /** @description Certified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelyingPartyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    suspendRelyingParty: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                rpId: components["schemas"]["RpId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipDecisionCreate"];
            };
        };
        responses: {
            /** @description Suspended */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelyingPartyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    listMembershipDecisions: {
        parameters: {
            query?: {
                /** @description Opaque cursor from a previous list response. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
                memberId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Decision trail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipDecisionListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
}
