/**
 * Routes for Download
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { downloadEvidencePack } from "../handlers/download.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function downloadRoutes(fastify: FastifyInstance) {
  // GET /v1/audit/evidence-packs/{packId}/download (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/audit/evidence-packs/:packId/download",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { packId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAuditDependenciesForRequest();
        await downloadEvidencePack(request, reply, deps);
      });
    }
  );


}
