/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/attestations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List attestations */
        get: operations["listAttestations"];
        put?: never;
        /** Request a purpose-scoped attestation (may issue or refuse) */
        post: operations["requestAttestation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/attestations/{attestationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get attestation */
        get: operations["getAttestation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/attestations/{attestationId}/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue signed attestation with liability and screening freshness */
        post: operations["issueAttestation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/attestations/{attestationId}/refuse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refuse incomplete or over-broad attestation request */
        post: operations["refuseAttestation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/attestations/{attestationId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke or invalidate an attestation */
        post: operations["revokeAttestation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/attestations/{attestationId}/document-recollect-exception": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record policy exception to re-collect documents despite valid attestation (BR-2) */
        post: operations["recordDocumentRecollectException"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        AttestationId: string;
        /** @enum {string} */
        AssuranceLevel: "IAL1" | "IAL2" | "IAL3";
        /** @enum {string} */
        LiabilityBearer: "identityProvider" | "relyingParty" | "subject";
        LiabilityAllocation: {
            bearer: components["schemas"]["LiabilityBearer"];
            ruleRef: string;
            notes?: string;
        };
        Attestation: {
            attestationId: components["schemas"]["AttestationId"];
            subjectId: string;
            identityProviderId: string;
            relyingPartyId: string;
            purpose?: string;
            attributeNames?: string[];
            assuranceLevel: components["schemas"]["AssuranceLevel"];
            /** @enum {string} */
            status: "pending" | "issued" | "refused" | "expired" | "revoked" | "disputed";
            liability: components["schemas"]["LiabilityAllocation"];
            screeningSnapshotId?: string;
            consentId?: string;
            /** Format: date-time */
            issuedAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            refuseReason?: string;
            documentRecollectExceptionReason?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        AttestationListResponse: {
            data: {
                items: components["schemas"]["Attestation"][];
                nextCursor?: string;
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        AttestationRequest: {
            subjectId: string;
            relyingPartyId: string;
            identityProviderId?: string;
            purpose: string;
            requiredAssuranceLevel: components["schemas"]["AssuranceLevel"];
            attributeNames: string[];
            consentId?: string;
        };
        AttestationResponse: {
            data: components["schemas"]["Attestation"];
            meta?: components["schemas"]["ResponseMeta"];
        };
        AttestationIssue: {
            liability: components["schemas"]["LiabilityAllocation"];
            screeningSnapshotId: string;
            consentId: string;
            attributeNames?: string[];
            /** Format: date-time */
            expiresAt?: string;
        };
        AttestationRefuse: {
            refuseReason: string;
        };
        AttestationRevoke: {
            reason: string;
        };
        DocumentRecollectException: {
            reason: string;
        };
    };
    responses: {
        /** @description Error (RFC 7807 Problem Details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Idempotency key reuse with different body, or state conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Semantically invalid request (e.g. PACK_EMPTY) */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Opaque cursor from a previous list response. */
        Cursor: string;
        /** @description Page size. */
        Limit: number;
        /**
         * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
         *     Replay with the same key and body returns the original result; different
         *     body with the same key yields 409.
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAttestations: {
        parameters: {
            query?: {
                /** @description Opaque cursor from a previous list response. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
                status?: "pending" | "issued" | "refused" | "expired" | "revoked" | "disputed";
                subjectId?: string;
                relyingPartyId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attestations page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttestationListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    requestAttestation: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttestationRequest"];
            };
        };
        responses: {
            /** @description Attestation issued or refused */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttestationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    getAttestation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attestationId: components["schemas"]["AttestationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attestation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttestationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    issueAttestation: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                attestationId: components["schemas"]["AttestationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttestationIssue"];
            };
        };
        responses: {
            /** @description Issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttestationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    refuseAttestation: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                attestationId: components["schemas"]["AttestationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttestationRefuse"];
            };
        };
        responses: {
            /** @description Refused */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttestationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    revokeAttestation: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                attestationId: components["schemas"]["AttestationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttestationRevoke"];
            };
        };
        responses: {
            /** @description Revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttestationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    recordDocumentRecollectException: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                attestationId: components["schemas"]["AttestationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentRecollectException"];
            };
        };
        responses: {
            /** @description Exception recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttestationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
}
