/**
 * InvalidateStaleScreeningDependents handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: screening
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { invalidateStaleScreeningDependents } from "@kyvora/api-server/domains/screening/handlers";
import type { ScreeningDDDDependencies } from "@kyvora/api-server/domains/screening";
import { createCreateInvalidateDependentRequest } from "@kyvora/factories/screening";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@kyvora/tests/shared";
import { SCREENING_USE_CASES } from "../__factories__/use-cases.js";

describe("InvalidateStaleScreeningDependents", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ScreeningDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ScreeningDDDDependencies>(
      SCREENING_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateInvalidateDependentRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeInvalidateStaleScreeningDependents, "execute").mockResolvedValue(useCaseResult);

    await invalidateStaleScreeningDependents(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeInvalidateStaleScreeningDependents.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
