/**
 * Routes for Attribute
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listSubjectAttributes, registerSubjectAttribute } from "../handlers/attribute.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function attributeRoutes(fastify: FastifyInstance) {
  // GET /v1/subjects/{subjectId}/attributes (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/subjects/:subjectId/attributes",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { subjectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSubjectsDependenciesForRequest();
        await listSubjectAttributes(request, reply, deps);
      });
    }
  );


  // POST /v1/subjects/{subjectId}/attributes (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/subjects/:subjectId/attributes",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { subjectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSubjectsDependenciesForRequest();
        await registerSubjectAttribute(request, reply, deps);
      });
    }
  );


}
