/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { refreshCycleRoutes } from "./refresh-cycle.routes.js";
export { attributeRoutes } from "./attribute.routes.js";
export { completeRoutes } from "./complete.routes.js";
export { legalEntityLinkRoutes } from "./legal-entity-link.routes.js";
export { subjectRoutes } from "./subject.routes.js";
