/**
 * Routes for Subject
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createSubject, getSubject, listSubjects, updateSubject } from "../handlers/subject.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function subjectRoutes(fastify: FastifyInstance) {
  // POST /v1/subjects (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/subjects",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSubjectsDependenciesForRequest();
        await createSubject(request, reply, deps);
      });
    }
  );


  // GET /v1/subjects (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/subjects",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSubjectsDependenciesForRequest();
        await listSubjects(request, reply, deps);
      });
    }
  );


  // GET /v1/subjects/{subjectId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/subjects/:subjectId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { subjectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSubjectsDependenciesForRequest();
        await getSubject(request, reply, deps);
      });
    }
  );


  // PATCH /v1/subjects/{subjectId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/subjects/:subjectId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { subjectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSubjectsDependenciesForRequest();
        await updateSubject(request, reply, deps);
      });
    }
  );


}
