/**
 * ExecuteGetAttestation - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetAttestation Use Case
 *
 * DDD: Application use case for get Attestation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetAttestationInput, GetAttestationOutput } from "../dto/attestation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { AttestationRepository } from "../ports/index.js";
import { NotFoundError, ValidationError } from "../errors/index.js";

export class ExecuteGetAttestation {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly attestation: AttestationRepository
  ) {}

  async execute(input: GetAttestationInput): Promise<GetAttestationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.attId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).attestationId) {
      throw new ValidationError("attestationId is required");
    }
    const attestationId = (input as any).attestationId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.attestation.getAttestation({ attestationId: attestationId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${attestationId}`);
    }

    return entity as GetAttestationOutput;
  }
}
