/**
 * ExecuteIssueAttestation - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * ExecuteIssueAttestation Use Case
 *
 * DDD: Application use case for get Issue.
 * Orchestrates the business flow using ports (interfaces).
 */
import type { IssueAttestationInput, IssueAttestationOutput } from "../dto/issue.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { IssueRepository } from "../ports/index.js";
export declare class ExecuteIssueAttestation {
    private readonly context;
    private readonly idGenerator;
    private readonly issue;
    constructor(context: ExecutionContextService, idGenerator: IdGeneratorService, issue: IssueRepository);
    execute(input: IssueAttestationInput): Promise<IssueAttestationOutput>;
}
