/**
 * ExecuteListAttestations - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListAttestations Use Case
 *
 * DDD: Application use case for list Attestation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListAttestationsInput, ListAttestationsOutput } from "../dto/attestation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { AttestationRepository } from "../ports/index.js";

export class ExecuteListAttestations {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly attestation: AttestationRepository
  ) {}

  async execute(input: ListAttestationsInput): Promise<ListAttestationsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.attId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.attestation.listAttestations({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListAttestationsOutput;
  }
}
