/**
 * ExecuteRevokeAttestation - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * ExecuteRevokeAttestation Use Case
 *
 * DDD: Application use case for get Revoke.
 * Orchestrates the business flow using ports (interfaces).
 */
import type { RevokeAttestationInput, RevokeAttestationOutput } from "../dto/revoke.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { RevokeRepository } from "../ports/index.js";
export declare class ExecuteRevokeAttestation {
    private readonly context;
    private readonly idGenerator;
    private readonly revoke;
    constructor(context: ExecutionContextService, idGenerator: IdGeneratorService, revoke: RevokeRepository);
    execute(input: RevokeAttestationInput): Promise<RevokeAttestationOutput>;
}
