/**
 * ExecuteListAttestations - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
export class ExecuteListAttestations {
    context;
    idGenerator;
    attestation;
    constructor(context, idGenerator, attestation) {
        this.context = context;
        this.idGenerator = idGenerator;
        this.attestation = attestation;
    }
    async execute(input) {
        // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
        const correlationId = this.idGenerator.attId();
        // All field names extracted from OpenAPI spec: none
        // List entities via repository
        const result = await this.attestation.listAttestations({ ...input, orgId: this.context.getOrgId(), correlationId });
        return result;
    }
}
