/**
 * ListIdentityProvider DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListIdentityProvidersParams } from "@kyvora/core/directory";

export function createListIdentityProviderRequest(overrides: Partial<ListIdentityProvidersParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
