/**
 * Attestation Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/attestations.openapi.types.js";
import { schemas } from "../schemas/attestations.schemas.js";

/**
 * Entity: AttestationEntity
 * Description: Represents the Attestation domain model.
 * Source: schemas.Attestation
 * Type: Domain Entity (API)
 */
export const AttestationEntitySchema = schemas.Attestation;
export type AttestationEntity = components["schemas"]["Attestation"];
