/**
 * DocumentRecollectException Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/attestations.openapi.types.js";
import { schemas } from "../schemas/attestations.schemas.js";

/**
 * Entity: DocumentRecollectExceptionEntity
 * Description: Represents the DocumentRecollectException domain model.
 * Source: schemas.DocumentRecollectException
 * Type: Domain Entity (API)
 */
export const DocumentRecollectExceptionEntitySchema = schemas.DocumentRecollectException;
export type DocumentRecollectExceptionEntity = components["schemas"]["DocumentRecollectException"];
