/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: screening
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Screening Domain Use Cases
 * 
 * List of all use case names for the screening domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const SCREENING_USE_CASES = [
  "executeGetScreeningSnapshot",
  "executeInvalidateStaleScreeningDependents",
  "executeListScreeningSnapshots",
  "executeRefreshScreeningSnapshot"
] as const;
