/**
 * Audit DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Audit Domain Module - Composition root
 *
 * DDD: Composition root for audit domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DownloadRepositoryAdapter,
  EvidencePackRepositoryAdapter,
} from "@kyvora/adapters/audit";
import { getIdGeneratorService } from "@kyvora/adapters";
import type { AdapterDynamoDBClient } from "@kyvora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteDownloadEvidencePack,
  ExecuteGenerateEvidencePack,
  ExecuteGetEvidencePack,
  ExecuteListEvidencePacks,
} from "@kyvora/services/audit/usecases";
// Ports (interfaces)
import type {
  DownloadRepository,
  EvidencePackRepository,
} from "@kyvora/services/audit/ports";

export interface AuditDomainModule {
  repos: {
    downloads: DownloadRepository;
    evidencePacks: EvidencePackRepository;
  };
  useCases: {
    downloads: {
      get: ExecuteDownloadEvidencePack;
    };
    evidencePacks: {
      get: ExecuteGetEvidencePack;
      list: ExecuteListEvidencePacks;
    };
  };
}

export function buildAuditDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AuditDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      downloads?: DownloadRepository;
      evidencePacks?: EvidencePackRepository;
    } = {};

    obj.downloads = new DownloadRepositoryAdapter(dynamoClient);
    obj.evidencePacks = new EvidencePackRepositoryAdapter(dynamoClient);
    return {
      downloads: obj.downloads!,
      evidencePacks: obj.evidencePacks!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    downloads: {
      get: new ExecuteDownloadEvidencePack(executionContext, idGenerator, repos.downloads),
    },
    evidencePacks: {
      get: new ExecuteGetEvidencePack(executionContext, idGenerator, repos.evidencePacks),
      list: new ExecuteListEvidencePacks(executionContext, idGenerator, repos.evidencePacks),
    },
  };
  return { repos, useCases: useCases as AuditDomainModule["useCases"] };
}
