/**
 * ApiKey Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import type { components } from "../openapi/identity.openapi.types.js";
/**
 * Entity: ApiKeyEntity
 * Description: Represents the ApiKey domain model.
 * Source: schemas.ApiKey
 * Type: Domain Entity (API)
 */
export declare const ApiKeyEntitySchema: any;
export type ApiKeyEntity = components["schemas"]["ApiKey"];
