/**
 * ConsentRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConsentRepository Port
 *
 * DDD: Application port for consentrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateConsentGrantInput, CreateConsentGrantOutput, GetConsentGrantInput, GetConsentGrantOutput, ListConsentGrantsInput, ListConsentGrantsOutput } from "../dto/consent.dto";
export interface ConsentRepository {
  listConsentGrants(input: ListConsentGrantsInput): Promise<ListConsentGrantsOutput>;
  createConsentGrant(input: CreateConsentGrantInput): Promise<CreateConsentGrantOutput>;
  getConsentGrant(input: GetConsentGrantInput): Promise<GetConsentGrantOutput>;
}

export type { CreateConsentGrantInput, CreateConsentGrantOutput, GetConsentGrantInput, GetConsentGrantOutput, ListConsentGrantsInput, ListConsentGrantsOutput } from "../dto/consent.dto";
