/**
 * FeeSchedule DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FeeSchedule DTOs
 *
 * DDD: Application DTOs for FeeSchedule use cases.
 */

import type { GetFeeScheduleParams, ListFeeSchedulesParams, UpsertFeeScheduleRequestInput } from "@kyvora/core/settlement/types";

export type ListFeeSchedulesInput = ListFeeSchedulesParams;

export type UpsertFeeScheduleInput = UpsertFeeScheduleRequestInput;

export type GetFeeScheduleInput = GetFeeScheduleParams;

export type ListFeeSchedulesOutput = {};

export type UpsertFeeScheduleOutput = {};

export type GetFeeScheduleOutput = {};
