/**
 * Invoice DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * Invoice DTOs
 *
 * DDD: Application DTOs for Invoice use cases.
 */
import type { GenerateSettlementInvoiceRequestInput, GetSettlementInvoiceParams, ListSettlementInvoicesParams } from "@kyvora/core/settlement/types";
export type ListSettlementInvoicesInput = ListSettlementInvoicesParams;
export type GenerateSettlementInvoiceInput = GenerateSettlementInvoiceRequestInput;
export type GetSettlementInvoiceInput = GetSettlementInvoiceParams;
export type ListSettlementInvoicesOutput = {};
export type GenerateSettlementInvoiceOutput = {};
export type GetSettlementInvoiceOutput = {};
