/**
 * ExecuteGetEvidencePack - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { NotFoundError, ValidationError } from "../errors";
export class ExecuteGetEvidencePack {
    context;
    idGenerator;
    evidencePack;
    constructor(context, idGenerator, evidencePack) {
        this.context = context;
        this.idGenerator = idGenerator;
        this.evidencePack = evidencePack;
    }
    async execute(input) {
        // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
        const correlationId = this.idGenerator.audId();
        // All field names extracted from OpenAPI spec: none
        // Validate input
        if (!input) {
            throw new ValidationError("Input is required");
        }
        if (!input.packId) {
            throw new ValidationError("packId is required");
        }
        const packId = input.packId;
        // Load entity via repository (pass correlation ID for response meta)
        const entity = await this.evidencePack.getEvidencePack({ packId: packId, orgId: this.context.getOrgId(), correlationId });
        if (!entity) {
            throw new NotFoundError(`Entity not found: ${packId}`);
        }
        return entity;
    }
}
