/**
 * ExecuteDownloadEvidencePack - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * ExecuteDownloadEvidencePack Use Case
 *
 * DDD: Application use case for get Download.
 * Orchestrates the business flow using ports (interfaces).
 */
import type { DownloadEvidencePackInput, DownloadEvidencePackOutput } from "../dto/download.dto";
import type { ExecutionContextService, IdGeneratorService } from "@kyvora/services/_shared/index.js";
import type { DownloadRepository } from "../ports/index.js";
export declare class ExecuteDownloadEvidencePack {
    private readonly context;
    private readonly idGenerator;
    private readonly download;
    constructor(context: ExecutionContextService, idGenerator: IdGeneratorService, download: DownloadRepository);
    execute(input: DownloadEvidencePackInput): Promise<DownloadEvidencePackOutput>;
}
