/**
 * RecordDocumentRecollectException handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { recordDocumentRecollectException } from "@kyvora/api-server/domains/attestations/handlers";
import type { AttestationsDDDDependencies } from "@kyvora/api-server/domains/attestations";
import { createDocumentRecollectException as createDocumentRecollectExceptionEntity } from "@kyvora/factories/attestations";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@kyvora/tests/shared";
import { ATTESTATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("RecordDocumentRecollectException", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AttestationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AttestationsDDDDependencies>(
      ATTESTATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createDocumentRecollectExceptionEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRecordDocumentRecollectException, "execute").mockResolvedValue(useCaseResult);

    await recordDocumentRecollectException(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRecordDocumentRecollectException.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
