/**
 * InvoiceRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * InvoiceRepository Port
 *
 * DDD: Application port for invoicerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */
import type { GenerateSettlementInvoiceInput, GenerateSettlementInvoiceOutput, GetSettlementInvoiceInput, GetSettlementInvoiceOutput, ListSettlementInvoicesInput, ListSettlementInvoicesOutput } from "../dto/invoice.dto";
export interface InvoiceRepository {
    listSettlementInvoices(input: ListSettlementInvoicesInput): Promise<ListSettlementInvoicesOutput>;
    generateSettlementInvoice(input: GenerateSettlementInvoiceInput): Promise<GenerateSettlementInvoiceOutput>;
    getSettlementInvoice(input: GetSettlementInvoiceInput): Promise<GetSettlementInvoiceOutput>;
}
export type { GenerateSettlementInvoiceInput, GenerateSettlementInvoiceOutput, GetSettlementInvoiceInput, GetSettlementInvoiceOutput, ListSettlementInvoicesInput, ListSettlementInvoicesOutput } from "../dto/invoice.dto";
