/**
 * SuspendRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SuspendRepository Port
 *
 * DDD: Application port for suspendrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { SuspendIdentityProviderInput, SuspendIdentityProviderOutput, SuspendRelyingPartyInput, SuspendRelyingPartyOutput } from "../dto/suspend.dto";
export interface SuspendRepository {
  suspendIdentityProvider(input: SuspendIdentityProviderInput): Promise<SuspendIdentityProviderOutput>;
  suspendRelyingParty(input: SuspendRelyingPartyInput): Promise<SuspendRelyingPartyOutput>;
}

export type { SuspendIdentityProviderInput, SuspendIdentityProviderOutput, SuspendRelyingPartyInput, SuspendRelyingPartyOutput } from "../dto/suspend.dto";
