/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { membershipDecisionRoutes } from "./membership-decision.routes.js";
export { certifyRoutes } from "./certify.routes.js";
export { identityProviderRoutes } from "./identity-provider.routes.js";
export { relyingPartyRoutes } from "./relying-party.routes.js";
export { suspendRoutes } from "./suspend.routes.js";
