/**
 * AttributeRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
export class AttributeRepositoryDdb {
    dynamoClient;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
    }
    async listSubjectAttributes(input) {
        // TODO: Implement using x-dynamodb metadata
        throw new Error("Not implemented - missing x-dynamodb metadata");
    }
    async registerSubjectAttribute(input) {
        // TODO: Implement using x-dynamodb metadata
        throw new Error("Not implemented - missing x-dynamodb metadata");
    }
}
