/**
 * LegalEntityLinkRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * LegalEntityLinkRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements LegalEntityLinkRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */
import type { LegalEntityLinkRepository } from "@kyvora/services/subjects";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
/**
 * LegalEntityLinkRepositoryAdapter
 *
 * Implements LegalEntityLinkRepository port for infrastructure layer.
 */
export declare class LegalEntityLinkRepositoryAdapter implements LegalEntityLinkRepository {
    private readonly dynamoClient;
    private readonly ddb;
    constructor(dynamoClient: AdapterDynamoDBClient);
    listLegalEntityLinks(input: Parameters<LegalEntityLinkRepository['listLegalEntityLinks']>[0]): Promise<Awaited<ReturnType<LegalEntityLinkRepository['listLegalEntityLinks']>>>;
    createLegalEntityLink(input: Parameters<LegalEntityLinkRepository['createLegalEntityLink']>[0]): Promise<Awaited<ReturnType<LegalEntityLinkRepository['createLegalEntityLink']>>>;
    unlinkLegalEntity(input: Parameters<LegalEntityLinkRepository['unlinkLegalEntity']>[0]): Promise<Awaited<ReturnType<LegalEntityLinkRepository['unlinkLegalEntity']>>>;
}
