/**
 * LegalEntityLinkRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { LegalEntityLinkRepositoryDdb } from "./legal-entity-link-repository.ddb.js";
/**
 * LegalEntityLinkRepositoryAdapter
 *
 * Implements LegalEntityLinkRepository port for infrastructure layer.
 */
export class LegalEntityLinkRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new LegalEntityLinkRepositoryDdb(this.dynamoClient);
    }
    async listLegalEntityLinks(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.listLegalEntityLinks(input);
    }
    async createLegalEntityLink(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.createLegalEntityLink(input);
    }
    async unlinkLegalEntity(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.unlinkLegalEntity(input);
    }
}
