/**
 * RefreshCycleRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { RefreshCycleRepositoryDdb } from "./refresh-cycle-repository.ddb.js";
/**
 * RefreshCycleRepositoryAdapter
 *
 * Implements RefreshCycleRepository port for infrastructure layer.
 */
export class RefreshCycleRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new RefreshCycleRepositoryDdb(this.dynamoClient);
    }
    async listRefreshCycles(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.listRefreshCycles(input);
    }
    async createRefreshCycle(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.createRefreshCycle(input);
    }
}
