/**
 * RefreshCycleRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * RefreshCycleRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RefreshCycleRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */
import type { RefreshCycleRepository } from "@kyvora/services/subjects";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
/**
 * RefreshCycleRepositoryAdapter
 *
 * Implements RefreshCycleRepository port for infrastructure layer.
 */
export declare class RefreshCycleRepositoryAdapter implements RefreshCycleRepository {
    private readonly dynamoClient;
    private readonly ddb;
    constructor(dynamoClient: AdapterDynamoDBClient);
    listRefreshCycles(input: Parameters<RefreshCycleRepository['listRefreshCycles']>[0]): Promise<Awaited<ReturnType<RefreshCycleRepository['listRefreshCycles']>>>;
    createRefreshCycle(input: Parameters<RefreshCycleRepository['createRefreshCycle']>[0]): Promise<Awaited<ReturnType<RefreshCycleRepository['createRefreshCycle']>>>;
}
