/**
 * SubjectRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * SubjectRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SubjectRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */
import type { SubjectRepository } from "@kyvora/services/subjects";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
/**
 * SubjectRepositoryAdapter
 *
 * Implements SubjectRepository port for infrastructure layer.
 */
export declare class SubjectRepositoryAdapter implements SubjectRepository {
    private readonly dynamoClient;
    private readonly ddb;
    constructor(dynamoClient: AdapterDynamoDBClient);
    listSubjects(input: Parameters<SubjectRepository['listSubjects']>[0]): Promise<Awaited<ReturnType<SubjectRepository['listSubjects']>>>;
    createSubject(input: Parameters<SubjectRepository['createSubject']>[0]): Promise<Awaited<ReturnType<SubjectRepository['createSubject']>>>;
    getSubject(input: Parameters<SubjectRepository['getSubject']>[0]): Promise<Awaited<ReturnType<SubjectRepository['getSubject']>>>;
    updateSubject(input: Parameters<SubjectRepository['updateSubject']>[0]): Promise<Awaited<ReturnType<SubjectRepository['updateSubject']>>>;
}
