/**
 * SubjectRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { SubjectRepositoryDdb } from "./subject-repository.ddb.js";
/**
 * SubjectRepositoryAdapter
 *
 * Implements SubjectRepository port for infrastructure layer.
 */
export class SubjectRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new SubjectRepositoryDdb(this.dynamoClient);
    }
    async listSubjects(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.listSubjects(input);
    }
    async createSubject(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.createSubject(input);
    }
    async getSubject(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.getSubject(input);
    }
    async updateSubject(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.updateSubject(input);
    }
}
