/**
 * Subject DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * Subject DTOs
 *
 * DDD: Application DTOs for Subject use cases.
 */
import type { CreateSubjectRequestInput, GetSubjectParams, ListSubjectsParams, UpdateSubjectParams, UpdateSubjectRequestInput } from "@kyvora/core/subjects/types";
export type ListSubjectsInput = ListSubjectsParams;
export type CreateSubjectInput = CreateSubjectRequestInput;
export type GetSubjectInput = GetSubjectParams;
export type UpdateSubjectInput = UpdateSubjectParams & UpdateSubjectRequestInput;
export type ListSubjectsOutput = {};
export type CreateSubjectOutput = {};
export type GetSubjectOutput = {};
export type UpdateSubjectOutput = {};
