/**
 * GetFeeSchedule handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getFeeSchedule } from "@kyvora/api-server/domains/settlement/handlers";
import type { SettlementDDDDependencies } from "@kyvora/api-server/domains/settlement";
import { createFeeSchedule as createFeeScheduleEntity } from "@kyvora/factories/settlement";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@kyvora/tests/shared";
import { SETTLEMENT_USE_CASES } from "../__factories__/use-cases.js";

describe("GetFeeSchedule", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SettlementDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SettlementDDDDependencies>(
      SETTLEMENT_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createFeeScheduleEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetFeeSchedule, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { scheduleId: entity.id };

    await getFeeSchedule(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetFeeSchedule.execute).toHaveBeenCalledWith(expect.objectContaining({ scheduleId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { scheduleId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetFeeSchedule, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getFeeSchedule(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
