/**
 * ExportRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * ExportRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ExportRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */
import type { ExportRepository } from "@kyvora/services/settlement";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
/**
 * ExportRepositoryAdapter
 *
 * Implements ExportRepository port for infrastructure layer.
 */
export declare class ExportRepositoryAdapter implements ExportRepository {
    private readonly dynamoClient;
    private readonly ddb;
    constructor(dynamoClient: AdapterDynamoDBClient);
    exportSettlementInvoice(input: Parameters<ExportRepository['exportSettlementInvoice']>[0]): Promise<Awaited<ReturnType<ExportRepository['exportSettlementInvoice']>>>;
}
