/**
 * ExportRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { ExportRepositoryDdb } from "./export-repository.ddb.js";
/**
 * ExportRepositoryAdapter
 *
 * Implements ExportRepository port for infrastructure layer.
 */
export class ExportRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new ExportRepositoryDdb(this.dynamoClient);
    }
    async exportSettlementInvoice(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.exportSettlementInvoice(input);
    }
}
