/**
 * FeeScheduleRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { FeeScheduleRepositoryDdb } from "./fee-schedule-repository.ddb.js";
/**
 * FeeScheduleRepositoryAdapter
 *
 * Implements FeeScheduleRepository port for infrastructure layer.
 */
export class FeeScheduleRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new FeeScheduleRepositoryDdb(this.dynamoClient);
    }
    async listFeeSchedules(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.listFeeSchedules(input);
    }
    async upsertFeeSchedule(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.upsertFeeSchedule(input);
    }
    async getFeeSchedule(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.getFeeSchedule(input);
    }
}
