/**
 * FeeScheduleRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * FeeScheduleRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements FeeScheduleRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */
import type { FeeScheduleRepository } from "@kyvora/services/settlement";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
/**
 * FeeScheduleRepositoryAdapter
 *
 * Implements FeeScheduleRepository port for infrastructure layer.
 */
export declare class FeeScheduleRepositoryAdapter implements FeeScheduleRepository {
    private readonly dynamoClient;
    private readonly ddb;
    constructor(dynamoClient: AdapterDynamoDBClient);
    listFeeSchedules(input: Parameters<FeeScheduleRepository['listFeeSchedules']>[0]): Promise<Awaited<ReturnType<FeeScheduleRepository['listFeeSchedules']>>>;
    upsertFeeSchedule(input: Parameters<FeeScheduleRepository['upsertFeeSchedule']>[0]): Promise<Awaited<ReturnType<FeeScheduleRepository['upsertFeeSchedule']>>>;
    getFeeSchedule(input: Parameters<FeeScheduleRepository['getFeeSchedule']>[0]): Promise<Awaited<ReturnType<FeeScheduleRepository['getFeeSchedule']>>>;
}
