/**
 * InvoiceRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { InvoiceRepositoryDdb } from "./invoice-repository.ddb.js";
/**
 * InvoiceRepositoryAdapter
 *
 * Implements InvoiceRepository port for infrastructure layer.
 */
export class InvoiceRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new InvoiceRepositoryDdb(this.dynamoClient);
    }
    async listSettlementInvoices(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.listSettlementInvoices(input);
    }
    async generateSettlementInvoice(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.generateSettlementInvoice(input);
    }
    async getSettlementInvoice(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.getSettlementInvoice(input);
    }
}
