/**
 * InvoiceRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * InvoiceRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements InvoiceRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */
import type { InvoiceRepository } from "@kyvora/services/settlement";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
/**
 * InvoiceRepositoryAdapter
 *
 * Implements InvoiceRepository port for infrastructure layer.
 */
export declare class InvoiceRepositoryAdapter implements InvoiceRepository {
    private readonly dynamoClient;
    private readonly ddb;
    constructor(dynamoClient: AdapterDynamoDBClient);
    listSettlementInvoices(input: Parameters<InvoiceRepository['listSettlementInvoices']>[0]): Promise<Awaited<ReturnType<InvoiceRepository['listSettlementInvoices']>>>;
    generateSettlementInvoice(input: Parameters<InvoiceRepository['generateSettlementInvoice']>[0]): Promise<Awaited<ReturnType<InvoiceRepository['generateSettlementInvoice']>>>;
    getSettlementInvoice(input: Parameters<InvoiceRepository['getSettlementInvoice']>[0]): Promise<Awaited<ReturnType<InvoiceRepository['getSettlementInvoice']>>>;
}
