/**
 * InvoiceRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * InvoiceRepositoryDdb
 *
 * DDD: Infrastructure adapter for Invoice repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */
import type { InvoiceRepository } from "@kyvora/services/settlement";
export declare class InvoiceRepositoryDdb implements InvoiceRepository {
    private readonly dynamoClient;
    constructor(dynamoClient: any);
    listSettlementInvoices(input: Parameters<InvoiceRepository['listSettlementInvoices']>[0]): Promise<Awaited<ReturnType<InvoiceRepository['listSettlementInvoices']>>>;
    generateSettlementInvoice(input: Parameters<InvoiceRepository['generateSettlementInvoice']>[0]): Promise<Awaited<ReturnType<InvoiceRepository['generateSettlementInvoice']>>>;
    getSettlementInvoice(input: Parameters<InvoiceRepository['getSettlementInvoice']>[0]): Promise<Awaited<ReturnType<InvoiceRepository['getSettlementInvoice']>>>;
}
