/**
 * InvalidateDependentRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: screening
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * InvalidateDependentRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements InvalidateDependentRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  InvalidateDependentRepository,
} from "@kyvora/services/screening";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { InvalidateDependentRepositoryDdb } from "./invalidate-dependent-repository.ddb.js";

/**
 * InvalidateDependentRepositoryAdapter
 *
 * Implements InvalidateDependentRepository port for infrastructure layer.
 */
export class InvalidateDependentRepositoryAdapter implements InvalidateDependentRepository {
  private readonly ddb: InvalidateDependentRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new InvalidateDependentRepositoryDdb(this.dynamoClient);
  }

  async invalidateStaleScreeningDependents(input: Parameters<InvalidateDependentRepository['invalidateStaleScreeningDependents']>[0]): Promise<Awaited<ReturnType<InvalidateDependentRepository['invalidateStaleScreeningDependents']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.invalidateStaleScreeningDependents(input);
  }
}
