/**
 * SnapshotRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: screening
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SnapshotRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SnapshotRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SnapshotRepository,
} from "@kyvora/services/screening";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SnapshotRepositoryDdb } from "./snapshot-repository.ddb.js";

/**
 * SnapshotRepositoryAdapter
 *
 * Implements SnapshotRepository port for infrastructure layer.
 */
export class SnapshotRepositoryAdapter implements SnapshotRepository {
  private readonly ddb: SnapshotRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SnapshotRepositoryDdb(this.dynamoClient);
  }

  async listScreeningSnapshots(input: Parameters<SnapshotRepository['listScreeningSnapshots']>[0]): Promise<Awaited<ReturnType<SnapshotRepository['listScreeningSnapshots']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listScreeningSnapshots(input);
  }

  async refreshScreeningSnapshot(input: Parameters<SnapshotRepository['refreshScreeningSnapshot']>[0]): Promise<Awaited<ReturnType<SnapshotRepository['refreshScreeningSnapshot']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.refreshScreeningSnapshot(input);
  }

  async getScreeningSnapshot(input: Parameters<SnapshotRepository['getScreeningSnapshot']>[0]): Promise<Awaited<ReturnType<SnapshotRepository['getScreeningSnapshot']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getScreeningSnapshot(input);
  }
}
