/**
 * SnapshotRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: screening
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * SnapshotRepositoryDdb
 *
 * DDD: Infrastructure adapter for Snapshot repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */
import type { SnapshotRepository } from "@kyvora/services/screening";
export declare class SnapshotRepositoryDdb implements SnapshotRepository {
    private readonly dynamoClient;
    constructor(dynamoClient: any);
    listScreeningSnapshots(input: Parameters<SnapshotRepository['listScreeningSnapshots']>[0]): Promise<Awaited<ReturnType<SnapshotRepository['listScreeningSnapshots']>>>;
    refreshScreeningSnapshot(input: Parameters<SnapshotRepository['refreshScreeningSnapshot']>[0]): Promise<Awaited<ReturnType<SnapshotRepository['refreshScreeningSnapshot']>>>;
    getScreeningSnapshot(input: Parameters<SnapshotRepository['getScreeningSnapshot']>[0]): Promise<Awaited<ReturnType<SnapshotRepository['getScreeningSnapshot']>>>;
}
