/**
 * DownloadRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * DownloadRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DownloadRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */
import type { DownloadRepository } from "@kyvora/services/audit";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
/**
 * DownloadRepositoryAdapter
 *
 * Implements DownloadRepository port for infrastructure layer.
 */
export declare class DownloadRepositoryAdapter implements DownloadRepository {
    private readonly dynamoClient;
    private readonly ddb;
    constructor(dynamoClient: AdapterDynamoDBClient);
    downloadEvidencePack(input: Parameters<DownloadRepository['downloadEvidencePack']>[0]): Promise<Awaited<ReturnType<DownloadRepository['downloadEvidencePack']>>>;
}
