/**
 * EvidencePackRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * EvidencePackRepositoryDdb
 *
 * DDD: Infrastructure adapter for EvidencePack repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */
import type { EvidencePackRepository } from "@kyvora/services/audit";
export declare class EvidencePackRepositoryDdb implements EvidencePackRepository {
    private readonly dynamoClient;
    constructor(dynamoClient: any);
    listEvidencePacks(input: Parameters<EvidencePackRepository['listEvidencePacks']>[0]): Promise<Awaited<ReturnType<EvidencePackRepository['listEvidencePacks']>>>;
    generateEvidencePack(input: Parameters<EvidencePackRepository['generateEvidencePack']>[0]): Promise<Awaited<ReturnType<EvidencePackRepository['generateEvidencePack']>>>;
    getEvidencePack(input: Parameters<EvidencePackRepository['getEvidencePack']>[0]): Promise<Awaited<ReturnType<EvidencePackRepository['getEvidencePack']>>>;
}
