/**
 * InvalidateDependent DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: screening
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * InvalidateDependent DTOs
 *
 * DDD: Application DTOs for InvalidateDependent use cases.
 */
import type { InvalidateStaleScreeningDependentsParams } from "@kyvora/core/screening/types";
export type InvalidateStaleScreeningDependentsInput = InvalidateStaleScreeningDependentsParams;
export type InvalidateStaleScreeningDependentsOutput = {};
