/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */
export interface paths {
    "/v1/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List identity subjects */
        get: operations["listSubjects"];
        put?: never;
        /** Register an identity subject */
        post: operations["createSubject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subjects/{subjectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get identity subject */
        get: operations["getSubject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update subject inclusion tier or display ref */
        patch: operations["updateSubject"];
        trace?: never;
    };
    "/v1/subjects/{subjectId}/attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List verified attributes (IdP-scoped, not a network honeypot) */
        get: operations["listSubjectAttributes"];
        put?: never;
        /** Register a verified attribute */
        post: operations["registerSubjectAttribute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subjects/{subjectId}/legal-entity-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List director/UBO links */
        get: operations["listLegalEntityLinks"];
        put?: never;
        /** Link an individual to a legal entity */
        post: operations["createLegalEntityLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/legal-entity-links/{linkId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unlink with audit */
        delete: operations["unlinkLegalEntity"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/refresh-cycles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List CDD refresh cycles */
        get: operations["listRefreshCycles"];
        put?: never;
        /** Schedule a refresh cycle */
        post: operations["createRefreshCycle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/refresh-cycles/{cycleId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete or force re-verify */
        post: operations["completeRefreshCycle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        SubjectId: string;
        IdentitySubject: {
            subjectId: components["schemas"]["SubjectId"];
            /** @enum {string} */
            subjectType: "individual" | "legalEntity";
            displayRef?: string;
            /** @enum {string} */
            inclusionTier?: "standard" | "alternativeEvidence";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        IdentitySubjectListResponse: {
            data: {
                items: components["schemas"]["IdentitySubject"][];
                nextCursor?: string;
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        IdentitySubjectCreate: {
            /** @enum {string} */
            subjectType: "individual" | "legalEntity";
            displayRef?: string;
            /** @enum {string} */
            inclusionTier?: "standard" | "alternativeEvidence";
        };
        IdentitySubjectResponse: {
            data: components["schemas"]["IdentitySubject"];
            meta?: components["schemas"]["ResponseMeta"];
        };
        IdentitySubjectUpdate: {
            displayRef?: string;
            /** @enum {string} */
            inclusionTier?: "standard" | "alternativeEvidence";
        };
        AttributeId: string;
        /** @enum {string} */
        AssuranceLevel: "IAL1" | "IAL2" | "IAL3";
        AttributeRecord: {
            attributeId: components["schemas"]["AttributeId"];
            subjectId: components["schemas"]["SubjectId"];
            name: string;
            valueHash?: string;
            assuranceLevel: components["schemas"]["AssuranceLevel"];
            /** Format: date-time */
            verifiedAt: string;
            /** Format: date-time */
            expiresAt?: string;
            source?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AttributeRecordListResponse: {
            data: {
                items: components["schemas"]["AttributeRecord"][];
                nextCursor?: string;
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        AttributeRecordCreate: {
            name: string;
            value: string;
            assuranceLevel: components["schemas"]["AssuranceLevel"];
            /** Format: date-time */
            expiresAt?: string;
            source?: string;
        };
        AttributeRecordResponse: {
            data: components["schemas"]["AttributeRecord"];
            meta?: components["schemas"]["ResponseMeta"];
        };
        LinkId: string;
        LegalEntityLink: {
            linkId: components["schemas"]["LinkId"];
            individualSubjectId: components["schemas"]["SubjectId"];
            legalEntitySubjectId: components["schemas"]["SubjectId"];
            /** @enum {string} */
            role: "director" | "ubo" | "signatory";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        LegalEntityLinkListResponse: {
            data: {
                items: components["schemas"]["LegalEntityLink"][];
                nextCursor?: string;
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        LegalEntityLinkCreate: {
            individualSubjectId: components["schemas"]["SubjectId"];
            legalEntitySubjectId: components["schemas"]["SubjectId"];
            /** @enum {string} */
            role: "director" | "ubo" | "signatory";
        };
        LegalEntityLinkResponse: {
            data: components["schemas"]["LegalEntityLink"];
            meta?: components["schemas"]["ResponseMeta"];
        };
        CycleId: string;
        RefreshCycle: {
            cycleId: components["schemas"]["CycleId"];
            subjectId: components["schemas"]["SubjectId"];
            /** Format: date-time */
            dueAt: string;
            /** @enum {string} */
            status: "scheduled" | "completed" | "overdue";
            changeSignals?: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        RefreshCycleListResponse: {
            data: {
                items: components["schemas"]["RefreshCycle"][];
                nextCursor?: string;
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        RefreshCycleCreate: {
            subjectId: components["schemas"]["SubjectId"];
            /** Format: date-time */
            dueAt: string;
            changeSignals?: string[];
        };
        RefreshCycleResponse: {
            data: components["schemas"]["RefreshCycle"];
            meta?: components["schemas"]["ResponseMeta"];
        };
        RefreshCycleComplete: {
            /** @enum {string} */
            status?: "completed" | "overdue";
        };
    };
    responses: {
        /** @description Error (RFC 7807 Problem Details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Idempotency key reuse with different body, or state conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Semantically invalid request (e.g. PACK_EMPTY) */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Opaque cursor from a previous list response. */
        Cursor: string;
        /** @description Page size. */
        Limit: number;
        /**
         * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
         *     Replay with the same key and body returns the original result; different
         *     body with the same key yields 409.
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSubjects: {
        parameters: {
            query?: {
                /** @description Opaque cursor from a previous list response. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
                subjectType?: "individual" | "legalEntity";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subjects page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentitySubjectListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    createSubject: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentitySubjectCreate"];
            };
        };
        responses: {
            /** @description Subject created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentitySubjectResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    getSubject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subjectId: components["schemas"]["SubjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subject */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentitySubjectResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    updateSubject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subjectId: components["schemas"]["SubjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentitySubjectUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentitySubjectResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    listSubjectAttributes: {
        parameters: {
            query?: {
                /** @description Opaque cursor from a previous list response. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                subjectId: components["schemas"]["SubjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attributes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeRecordListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    registerSubjectAttribute: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                subjectId: components["schemas"]["SubjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttributeRecordCreate"];
            };
        };
        responses: {
            /** @description Attribute registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeRecordResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    listLegalEntityLinks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subjectId: components["schemas"]["SubjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Links */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalEntityLinkListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    createLegalEntityLink: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                subjectId: components["schemas"]["SubjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LegalEntityLinkCreate"];
            };
        };
        responses: {
            /** @description Linked */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalEntityLinkResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    unlinkLegalEntity: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                linkId: components["schemas"]["LinkId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unlinked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    listRefreshCycles: {
        parameters: {
            query?: {
                /** @description Opaque cursor from a previous list response. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
                status?: "scheduled" | "completed" | "overdue";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refresh cycles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshCycleListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    createRefreshCycle: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshCycleCreate"];
            };
        };
        responses: {
            /** @description Scheduled */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshCycleResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
    completeRefreshCycle: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                cycleId: components["schemas"]["CycleId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshCycleComplete"];
            };
        };
        responses: {
            /** @description Completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshCycleResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            default: components["responses"]["Problem"];
        };
    };
}
