/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./create-consent-grant.handler.test.js";
export * from "./get-consent-grant.handler.test.js";
export * from "./list-consent-grants.handler.test.js";
