/**
 * Disputes DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Disputes Domain Module - Composition root
 *
 * DDD: Composition root for disputes domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DisputeRepositoryAdapter,
  ResolveRepositoryAdapter,
} from "@kyvora/adapters/disputes";
import { getIdGeneratorService } from "@kyvora/adapters";
import type { AdapterDynamoDBClient } from "@kyvora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetDisputeCase,
  ExecuteListDisputeCases,
  ExecuteOpenDisputeCase,
  ExecuteResolveDisputeCase,
} from "@kyvora/services/disputes/usecases";
// Ports (interfaces)
import type {
  DisputeRepository,
  ResolveRepository,
} from "@kyvora/services/disputes/ports";

export interface DisputesDomainModule {
  repos: {
    disputes: DisputeRepository;
    resolves: ResolveRepository;
  };
  useCases: {
    disputes: {
      get: ExecuteGetDisputeCase;
      list: ExecuteListDisputeCases;
    };
    resolves: {
      get: ExecuteResolveDisputeCase;
    };
  };
}

export function buildDisputesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): DisputesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      disputes?: DisputeRepository;
      resolves?: ResolveRepository;
    } = {};

    obj.disputes = new DisputeRepositoryAdapter(dynamoClient);
    obj.resolves = new ResolveRepositoryAdapter(dynamoClient);
    return {
      disputes: obj.disputes!,
      resolves: obj.resolves!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    disputes: {
      get: new ExecuteGetDisputeCase(executionContext, idGenerator, repos.disputes),
      list: new ExecuteListDisputeCases(executionContext, idGenerator, repos.disputes),
    },
    resolves: {
      get: new ExecuteResolveDisputeCase(executionContext, idGenerator, repos.resolves),
    },
  };
  return { repos, useCases: useCases as DisputesDomainModule["useCases"] };
}
