/**
 * LegalEntityLink Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import type { components } from "../openapi/subjects.openapi.types.js";
/**
 * Entity: LegalEntityLinkEntity
 * Description: Represents the LegalEntityLink domain model.
 * Source: schemas.LegalEntityLink
 * Type: Domain Entity (API)
 */
export declare const LegalEntityLinkEntitySchema: any;
export type LegalEntityLinkEntity = components["schemas"]["LegalEntityLink"];
