/**
 * GetDownload DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { DownloadEvidencePackParams } from "@kyvora/core/audit";

export function createGetDownloadRequest(overrides: Partial<DownloadEvidencePackParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
