/**
 * Handlers for FeeSchedule
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SettlementDomainModule } from "../dependencies/settlement-ddd.dependencies.js";
import type { GetFeeScheduleInput, ListFeeSchedulesInput, UpsertFeeScheduleInput } from "@kyvora/services/settlement";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/settlement/fee-schedules
 * Operation: listFeeSchedules
 */
export async function listFeeSchedules(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], identityProviderId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: SettlementDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListFeeSchedulesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.feeSchedules.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/settlement/fee-schedules
 * Operation: upsertFeeSchedule
 */
export async function upsertFeeSchedule(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: SettlementDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpsertFeeScheduleInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.feeSchedules.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/settlement/fee-schedules/{scheduleId}
 * Operation: getFeeSchedule
 */
export async function getFeeSchedule(
  request: FastifyRequest<{ Params: { scheduleId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SettlementDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetFeeScheduleInput = {
    scheduleId: request.params.scheduleId,
  };
  const result = await deps.useCases.feeSchedules.get.execute(input);
  return reply.code(200).send(result);
}


