/**
 * Handlers for Invoice
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SettlementDomainModule } from "../dependencies/settlement-ddd.dependencies.js";
import type { GenerateSettlementInvoiceInput, GetSettlementInvoiceInput, ListSettlementInvoicesInput } from "@kyvora/services/settlement";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/settlement/invoices
 * Operation: listSettlementInvoices
 */
export async function listSettlementInvoices(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: SettlementDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListSettlementInvoicesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.invoices.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/settlement/invoices
 * Operation: generateSettlementInvoice
 */
export async function generateSettlementInvoice(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: SettlementDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GenerateSettlementInvoiceInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.invoices.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/settlement/invoices/{invoiceId}
 * Operation: getSettlementInvoice
 */
export async function getSettlementInvoice(
  request: FastifyRequest<{ Params: { invoiceId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SettlementDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetSettlementInvoiceInput = {
    invoiceId: request.params.invoiceId,
  };
  const result = await deps.useCases.invoices.get.execute(input);
  return reply.code(200).send(result);
}


