/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Settlement Domain Use Cases
 * 
 * List of all use case names for the settlement domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const SETTLEMENT_USE_CASES = [
  "executeExportSettlementInvoice",
  "executeGenerateSettlementInvoice",
  "executeGetFeeSchedule",
  "executeGetSettlementInvoice",
  "executeListFeeSchedules",
  "executeListSettlementInvoices",
  "executeUpsertFeeSchedule"
] as const;
