/**
 * Handlers for Attribute
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SubjectsDomainModule } from "../dependencies/subjects-ddd.dependencies.js";
import type { ListSubjectAttributesInput, RegisterSubjectAttributeInput } from "@kyvora/services/subjects";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/subjects/{subjectId}/attributes
 * Operation: listSubjectAttributes
 */
export async function listSubjectAttributes(
  request: FastifyRequest<{ Params: { subjectId: string }; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: SubjectsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListSubjectAttributesInput = {
    subjectId: request.params.subjectId,
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.attributes.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/subjects/{subjectId}/attributes
 * Operation: registerSubjectAttribute
 */
export async function registerSubjectAttribute(
  request: FastifyRequest<{ Params: { subjectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SubjectsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RegisterSubjectAttributeInput = {
    subjectId: request.params.subjectId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.attributes.create.execute(input);
  return reply.code(201).send(result);
}


