/**
 * Handlers index
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./attribute.handlers.js";
export * from "./complete.handlers.js";
export * from "./legal-entity-link.handlers.js";
export * from "./refresh-cycle.handlers.js";
export * from "./subject.handlers.js";
