/**
 * Handlers for RefreshCycle
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SubjectsDomainModule } from "../dependencies/subjects-ddd.dependencies.js";
import type { CreateRefreshCycleInput, ListRefreshCyclesInput } from "@kyvora/services/subjects";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/refresh-cycles
 * Operation: listRefreshCycles
 */
export async function listRefreshCycles(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: SubjectsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListRefreshCyclesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.refreshCycles.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/refresh-cycles
 * Operation: createRefreshCycle
 */
export async function createRefreshCycle(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: SubjectsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateRefreshCycleInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.refreshCycles.create.execute(input);
  return reply.code(201).send(result);
}


