/**
 * CanCreate Policy - Business rule
 *
 * Generated by Policy Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * CanCreate Policy
 *
 * DDD: Application policy for determining if create operations are allowed.
 */
export declare const CanCreate: {
    allow(account: {
        status?: string;
    }, _providerType: string): boolean;
};
