/**
 * AttestationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AttestationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AttestationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AttestationRepository,
} from "@kyvora/services/attestations";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AttestationRepositoryDdb } from "./attestation-repository.ddb.js";

/**
 * AttestationRepositoryAdapter
 *
 * Implements AttestationRepository port for infrastructure layer.
 */
export class AttestationRepositoryAdapter implements AttestationRepository {
  private readonly ddb: AttestationRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AttestationRepositoryDdb(this.dynamoClient);
  }

  async listAttestations(input: Parameters<AttestationRepository['listAttestations']>[0]): Promise<Awaited<ReturnType<AttestationRepository['listAttestations']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAttestations(input);
  }

  async requestAttestation(input: Parameters<AttestationRepository['requestAttestation']>[0]): Promise<Awaited<ReturnType<AttestationRepository['requestAttestation']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.requestAttestation(input);
  }

  async getAttestation(input: Parameters<AttestationRepository['getAttestation']>[0]): Promise<Awaited<ReturnType<AttestationRepository['getAttestation']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getAttestation(input);
  }
}
