/**
 * AttestationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * AttestationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AttestationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */
import type { AttestationRepository } from "@kyvora/services/attestations";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
/**
 * AttestationRepositoryAdapter
 *
 * Implements AttestationRepository port for infrastructure layer.
 */
export declare class AttestationRepositoryAdapter implements AttestationRepository {
    private readonly dynamoClient;
    private readonly ddb;
    constructor(dynamoClient: AdapterDynamoDBClient);
    listAttestations(input: Parameters<AttestationRepository['listAttestations']>[0]): Promise<Awaited<ReturnType<AttestationRepository['listAttestations']>>>;
    requestAttestation(input: Parameters<AttestationRepository['requestAttestation']>[0]): Promise<Awaited<ReturnType<AttestationRepository['requestAttestation']>>>;
    getAttestation(input: Parameters<AttestationRepository['getAttestation']>[0]): Promise<Awaited<ReturnType<AttestationRepository['getAttestation']>>>;
}
