/**
 * AttestationRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
export class AttestationRepositoryDdb {
    dynamoClient;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
    }
    async listAttestations(input) {
        // TODO: Implement using x-dynamodb metadata
        throw new Error("Not implemented - missing x-dynamodb metadata");
    }
    async requestAttestation(input) {
        // TODO: Implement using x-dynamodb metadata
        throw new Error("Not implemented - missing x-dynamodb metadata");
    }
    async getAttestation(input) {
        // TODO: Implement using x-dynamodb metadata
        throw new Error("Not implemented - missing x-dynamodb metadata");
    }
}
