/**
 * DocumentRecollectExceptionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * DocumentRecollectExceptionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DocumentRecollectExceptionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */
import type { DocumentRecollectExceptionRepository } from "@kyvora/services/attestations";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
/**
 * DocumentRecollectExceptionRepositoryAdapter
 *
 * Implements DocumentRecollectExceptionRepository port for infrastructure layer.
 */
export declare class DocumentRecollectExceptionRepositoryAdapter implements DocumentRecollectExceptionRepository {
    private readonly dynamoClient;
    private readonly ddb;
    constructor(dynamoClient: AdapterDynamoDBClient);
    recordDocumentRecollectException(input: Parameters<DocumentRecollectExceptionRepository['recordDocumentRecollectException']>[0]): Promise<Awaited<ReturnType<DocumentRecollectExceptionRepository['recordDocumentRecollectException']>>>;
}
