/**
 * DocumentRecollectExceptionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { DocumentRecollectExceptionRepositoryDdb } from "./document-recollect-exception-repository.ddb.js";
/**
 * DocumentRecollectExceptionRepositoryAdapter
 *
 * Implements DocumentRecollectExceptionRepository port for infrastructure layer.
 */
export class DocumentRecollectExceptionRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new DocumentRecollectExceptionRepositoryDdb(this.dynamoClient);
    }
    async recordDocumentRecollectException(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.recordDocumentRecollectException(input);
    }
}
