/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
export * from "./attestation-repository.ddb.js";
export * from "./document-recollect-exception-repository.ddb.js";
export * from "./issue-repository.ddb.js";
export * from "./refuse-repository.ddb.js";
export * from "./revoke-repository.ddb.js";
export * from "./attestation-repository.adapter.js";
export * from "./document-recollect-exception-repository.adapter.js";
export * from "./issue-repository.adapter.js";
export * from "./refuse-repository.adapter.js";
export * from "./revoke-repository.adapter.js";
