/**
 * IssueRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * IssueRepositoryDdb
 *
 * DDD: Infrastructure adapter for Issue repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */
import type { IssueRepository } from "@kyvora/services/attestations";
export declare class IssueRepositoryDdb implements IssueRepository {
    private readonly dynamoClient;
    constructor(dynamoClient: any);
    issueAttestation(input: Parameters<IssueRepository['issueAttestation']>[0]): Promise<Awaited<ReturnType<IssueRepository['issueAttestation']>>>;
}
