/**
 * RefuseRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * RefuseRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RefuseRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */
import type { RefuseRepository } from "@kyvora/services/attestations";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
/**
 * RefuseRepositoryAdapter
 *
 * Implements RefuseRepository port for infrastructure layer.
 */
export declare class RefuseRepositoryAdapter implements RefuseRepository {
    private readonly dynamoClient;
    private readonly ddb;
    constructor(dynamoClient: AdapterDynamoDBClient);
    refuseAttestation(input: Parameters<RefuseRepository['refuseAttestation']>[0]): Promise<Awaited<ReturnType<RefuseRepository['refuseAttestation']>>>;
}
