/**
 * RefuseRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { RefuseRepositoryDdb } from "./refuse-repository.ddb.js";
/**
 * RefuseRepositoryAdapter
 *
 * Implements RefuseRepository port for infrastructure layer.
 */
export class RefuseRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new RefuseRepositoryDdb(this.dynamoClient);
    }
    async refuseAttestation(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.refuseAttestation(input);
    }
}
