/**
 * RelyingParty Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { RelyingPartyEntity } from "@kyvora/core/directory/models/index.js";
import { directorySchemas } from "@kyvora/core/directory";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "dir";

export function createRelyingParty(overrides: Partial<RelyingPartyEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    allowedPurposes: overrides.allowedPurposes ?? [],
    legalName: overrides.legalName ?? faker.lorem.word(),
    rpId: overrides.rpId ?? `rly_${ulid().toLowerCase()}`,
    status: overrides.status ?? "active",
    ...overrides,
  };

  return directorySchemas.RelyingParty.parse(raw);
}

export function relyingPartyBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createRelyingParty(overrides));
}
