/**
 * CertifyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { CertifyRepositoryDdb } from "./certify-repository.ddb.js";
/**
 * CertifyRepositoryAdapter
 *
 * Implements CertifyRepository port for infrastructure layer.
 */
export class CertifyRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new CertifyRepositoryDdb(this.dynamoClient);
    }
    async certifyIdentityProvider(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.certifyIdentityProvider(input);
    }
    async certifyRelyingParty(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.certifyRelyingParty(input);
    }
}
