/**
 * CertifyRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * CertifyRepositoryDdb
 *
 * DDD: Infrastructure adapter for Certify repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */
import type { CertifyRepository } from "@kyvora/services/directory";
export declare class CertifyRepositoryDdb implements CertifyRepository {
    private readonly dynamoClient;
    constructor(dynamoClient: any);
    certifyIdentityProvider(input: Parameters<CertifyRepository['certifyIdentityProvider']>[0]): Promise<Awaited<ReturnType<CertifyRepository['certifyIdentityProvider']>>>;
    certifyRelyingParty(input: Parameters<CertifyRepository['certifyRelyingParty']>[0]): Promise<Awaited<ReturnType<CertifyRepository['certifyRelyingParty']>>>;
}
