/**
 * IdentityProviderRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IdentityProviderRepositoryDdb
 *
 * DDD: Infrastructure adapter for IdentityProvider repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import type { IdentityProviderRepository } from "@kyvora/services/directory";

export class IdentityProviderRepositoryDdb implements IdentityProviderRepository {
  constructor(private readonly dynamoClient: any) {}

  async listIdentityProviders(input: Parameters<IdentityProviderRepository['listIdentityProviders']>[0]): Promise<Awaited<ReturnType<IdentityProviderRepository['listIdentityProviders']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }

  async registerIdentityProvider(input: Parameters<IdentityProviderRepository['registerIdentityProvider']>[0]): Promise<Awaited<ReturnType<IdentityProviderRepository['registerIdentityProvider']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }

  async getIdentityProvider(input: Parameters<IdentityProviderRepository['getIdentityProvider']>[0]): Promise<Awaited<ReturnType<IdentityProviderRepository['getIdentityProvider']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }
}
