/**
 * IdentityProviderRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IdentityProviderRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements IdentityProviderRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  IdentityProviderRepository,
} from "@kyvora/services/directory";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { IdentityProviderRepositoryDdb } from "./identity-provider-repository.ddb.js";

/**
 * IdentityProviderRepositoryAdapter
 *
 * Implements IdentityProviderRepository port for infrastructure layer.
 */
export class IdentityProviderRepositoryAdapter implements IdentityProviderRepository {
  private readonly ddb: IdentityProviderRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new IdentityProviderRepositoryDdb(this.dynamoClient);
  }

  async listIdentityProviders(input: Parameters<IdentityProviderRepository['listIdentityProviders']>[0]): Promise<Awaited<ReturnType<IdentityProviderRepository['listIdentityProviders']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listIdentityProviders(input);
  }

  async registerIdentityProvider(input: Parameters<IdentityProviderRepository['registerIdentityProvider']>[0]): Promise<Awaited<ReturnType<IdentityProviderRepository['registerIdentityProvider']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.registerIdentityProvider(input);
  }

  async getIdentityProvider(input: Parameters<IdentityProviderRepository['getIdentityProvider']>[0]): Promise<Awaited<ReturnType<IdentityProviderRepository['getIdentityProvider']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getIdentityProvider(input);
  }
}
