/**
 * MembershipDecisionRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * MembershipDecisionRepositoryDdb
 *
 * DDD: Infrastructure adapter for MembershipDecision repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */
import type { MembershipDecisionRepository } from "@kyvora/services/directory";
export declare class MembershipDecisionRepositoryDdb implements MembershipDecisionRepository {
    private readonly dynamoClient;
    constructor(dynamoClient: any);
    listMembershipDecisions(input: Parameters<MembershipDecisionRepository['listMembershipDecisions']>[0]): Promise<Awaited<ReturnType<MembershipDecisionRepository['listMembershipDecisions']>>>;
}
