/**
 * RelyingPartyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * RelyingPartyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RelyingPartyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */
import type { RelyingPartyRepository } from "@kyvora/services/directory";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
/**
 * RelyingPartyRepositoryAdapter
 *
 * Implements RelyingPartyRepository port for infrastructure layer.
 */
export declare class RelyingPartyRepositoryAdapter implements RelyingPartyRepository {
    private readonly dynamoClient;
    private readonly ddb;
    constructor(dynamoClient: AdapterDynamoDBClient);
    listRelyingParties(input: Parameters<RelyingPartyRepository['listRelyingParties']>[0]): Promise<Awaited<ReturnType<RelyingPartyRepository['listRelyingParties']>>>;
    registerRelyingParty(input: Parameters<RelyingPartyRepository['registerRelyingParty']>[0]): Promise<Awaited<ReturnType<RelyingPartyRepository['registerRelyingParty']>>>;
    getRelyingParty(input: Parameters<RelyingPartyRepository['getRelyingParty']>[0]): Promise<Awaited<ReturnType<RelyingPartyRepository['getRelyingParty']>>>;
}
