/**
 * RelyingPartyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { RelyingPartyRepositoryDdb } from "./relying-party-repository.ddb.js";
/**
 * RelyingPartyRepositoryAdapter
 *
 * Implements RelyingPartyRepository port for infrastructure layer.
 */
export class RelyingPartyRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new RelyingPartyRepositoryDdb(this.dynamoClient);
    }
    async listRelyingParties(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.listRelyingParties(input);
    }
    async registerRelyingParty(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.registerRelyingParty(input);
    }
    async getRelyingParty(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.getRelyingParty(input);
    }
}
