/**
 * SuspendRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { SuspendRepositoryDdb } from "./suspend-repository.ddb.js";
/**
 * SuspendRepositoryAdapter
 *
 * Implements SuspendRepository port for infrastructure layer.
 */
export class SuspendRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new SuspendRepositoryDdb(this.dynamoClient);
    }
    async suspendIdentityProvider(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.suspendIdentityProvider(input);
    }
    async suspendRelyingParty(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.suspendRelyingParty(input);
    }
}
