/**
 * ListRefreshCycle DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: subjects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListRefreshCyclesParams } from "@kyvora/core/subjects";

export function createListRefreshCycleRequest(overrides: Partial<ListRefreshCyclesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
