/**
 * Domain Dependency Injection Hook
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Performance-optimized centralized dependency injection that matches domain from path
 * and injects only the needed domain dependencies. Dependencies are cached per domain.
 *
 * Usage:
 * ```typescript
 * fastify.addHook("preHandler", injectDomainDependencies);
 * ```
 *
 * Access dependencies in routes:
 * ```typescript
 * const deps = getDomainDeps(request, "content");
 * ```
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AdapterDynamoDBClient } from "@kyvora/adapters";
import {
  DynamoDBClient,
  BatchWriteItemCommand,
} from "@aws-sdk/client-dynamodb";
import {
  DynamoDBDocumentClient,
  QueryCommand,
  GetCommand,
  PutCommand,
  UpdateCommand,
  DeleteCommand,
  ScanCommand,
  TransactWriteCommand,
} from "@aws-sdk/lib-dynamodb";
import type {
  QueryCommandInput,
  QueryCommandOutput,
  GetCommandInput,
  GetCommandOutput,
  PutCommandInput,
  PutCommandOutput,
  UpdateCommandInput,
  UpdateCommandOutput,
  DeleteCommandInput,
  DeleteCommandOutput,
  ScanCommandInput,
  ScanCommandOutput,
  TransactWriteCommandInput,
  TransactWriteCommandOutput,
} from "@aws-sdk/lib-dynamodb";
import type {
  BatchWriteItemCommandInput,
  BatchWriteItemCommandOutput,
} from "@aws-sdk/client-dynamodb";
import { getAwsCredentialProvider } from "../infrastructure/aws-credentials.js";

// Import all domain builder functions and types from barrel export
import {
  buildAttestationsDomainModule,
  buildAuditDomainModule,
  buildConsentsDomainModule,
  buildDirectoryDomainModule,
  buildDisputesDomainModule,
  buildIdentityDomainModule,
  buildScreeningDomainModule,
  buildSettlementDomainModule,
  buildSubjectsDomainModule,
} from "../../domains/index.js";
import type {
  AttestationsDomainModule,
  AuditDomainModule,
  ConsentsDomainModule,
  DirectoryDomainModule,
  DisputesDomainModule,
  IdentityDomainModule,
  ScreeningDomainModule,
  SettlementDomainModule,
  SubjectsDomainModule,
} from "../../domains/index.js";

/**
 * Performance-optimized dependency cache
 */
const dependencyCache = new Map<string, any>();

function getCacheKey(domain: string): string {
  return domain;
}

/**
 * Wrapper for DynamoDBDocumentClient that implements AdapterDynamoDBClient interface
 */
class DynamoDBClientAdapter implements AdapterDynamoDBClient {
  constructor(private readonly docClient: DynamoDBDocumentClient) {}

  async query(input: QueryCommandInput): Promise<QueryCommandOutput> {
    return this.docClient.send(new QueryCommand(input));
  }

  async get(input: GetCommandInput): Promise<GetCommandOutput> {
    return this.docClient.send(new GetCommand(input));
  }

  async put(input: PutCommandInput): Promise<PutCommandOutput> {
    return this.docClient.send(new PutCommand(input));
  }

  async update(input: UpdateCommandInput): Promise<UpdateCommandOutput> {
    return this.docClient.send(new UpdateCommand(input));
  }

  async delete(input: DeleteCommandInput): Promise<DeleteCommandOutput> {
    return this.docClient.send(new DeleteCommand(input));
  }

  async scan(input: ScanCommandInput): Promise<ScanCommandOutput> {
    return this.docClient.send(new ScanCommand(input));
  }

  async batchWrite(
    input: BatchWriteItemCommandInput,
  ): Promise<BatchWriteItemCommandOutput> {
    return this.docClient.send(new BatchWriteItemCommand(input));
  }

  async transactWrite(
    input: TransactWriteCommandInput,
  ): Promise<TransactWriteCommandOutput> {
    return this.docClient.send(new TransactWriteCommand(input));
  }

  async send<T>(command: T): Promise<any> {
    return this.docClient.send(command as any);
  }
}

let dynamoClientInstance: AdapterDynamoDBClient | null = null;

export function getDynamoClientInstance(): AdapterDynamoDBClient {
  if (!dynamoClientInstance) {
    const region =
      process.env.AWS_REGION || process.env.AWS_DEFAULT_REGION || "us-east-1";
    const clientConfig: {
      region: string;
      endpoint?: string;
      credentials?: import("@aws-sdk/types").AwsCredentialIdentityProvider;
    } = { region };

    const credentialProvider = getAwsCredentialProvider();
    if (credentialProvider) clientConfig.credentials = credentialProvider;

    if (process.env.AWS_ENDPOINT_URL || process.env.LOCALSTACK_ENDPOINT) {
      clientConfig.endpoint =
        process.env.AWS_ENDPOINT_URL || process.env.LOCALSTACK_ENDPOINT;
    }

    const client = new DynamoDBClient(clientConfig);
    const docClient = DynamoDBDocumentClient.from(client);
    dynamoClientInstance = new DynamoDBClientAdapter(docClient);
  }
  return dynamoClientInstance;
}

/**
 * Domain path patterns - maps URL path segments to domain names
 */
const DOMAIN_PATH_PATTERNS: Array<{ pattern: RegExp; domain: string }> = [
  { pattern: /\/auth\//, domain: "identity" }, // Auth routes belong to identity domain
  { pattern: /\/attestations\//, domain: "attestations" },
  { pattern: /\/audit\//, domain: "audit" },
  { pattern: /\/consents\//, domain: "consents" },
  { pattern: /\/directory\//, domain: "directory" },
  { pattern: /\/disputes\//, domain: "disputes" },
  { pattern: /\/identity\//, domain: "identity" },
  { pattern: /\/screening\//, domain: "screening" },
  { pattern: /\/settlement\//, domain: "settlement" },
  { pattern: /\/subjects\//, domain: "subjects" },
];

function detectDomainFromPath(path: string): string | null {
  for (const { pattern, domain } of DOMAIN_PATH_PATTERNS) {
    if (pattern.test(path)) {
      return domain;
    }
  }
  return null;
}

/**
 * Inject domain dependencies into request object
 */
export async function injectDomainDependencies(
  request: FastifyRequest,
  reply: FastifyReply,
): Promise<void> {
  const orgId = (request as any).effectiveOrgId;

  if (!orgId) {
    reply.status(401).send({
      error: "Unauthorized",
      message:
        "Missing orgId. setOrgContext hook must run before injectDomainDependencies.",
    });
    return;
  }

  const path = request.url;
  const domain = detectDomainFromPath(path);

  if (!domain) {
    return;
  }

  if (!(request as any).deps) {
    (request as any).deps = {};
  }

  const cacheKey = getCacheKey(domain);
  let domainDeps = dependencyCache.get(cacheKey);

  if (!domainDeps) {
    const dynamoClient = getDynamoClientInstance();

    switch (domain) {
      case "attestations":
        domainDeps = buildAttestationsDomainModule(dynamoClient);
        break;
      case "audit":
        domainDeps = buildAuditDomainModule(dynamoClient);
        break;
      case "consents":
        domainDeps = buildConsentsDomainModule(dynamoClient);
        break;
      case "directory":
        domainDeps = buildDirectoryDomainModule(dynamoClient);
        break;
      case "disputes":
        domainDeps = buildDisputesDomainModule(dynamoClient);
        break;
      case "identity":
        domainDeps = buildIdentityDomainModule(dynamoClient);
        break;
      case "screening":
        domainDeps = buildScreeningDomainModule(dynamoClient);
        break;
      case "settlement":
        domainDeps = buildSettlementDomainModule(dynamoClient);
        break;
      case "subjects":
        domainDeps = buildSubjectsDomainModule(dynamoClient);
        break;
      default:
        return;
    }

    dependencyCache.set(cacheKey, domainDeps);
  }

  (request as any).deps[domain] = domainDeps;
}

/**
 * Type-safe helper to get domain dependencies from request
 */
export function getDomainDeps<T extends keyof DomainDependencies>(
  request: FastifyRequest,
  domain: T,
): DomainDependencies[T] {
  const deps = (request as any).deps;
  if (!deps || !deps[domain]) {
    throw new Error(
      `${domain} dependencies not found. Ensure injectDomainDependencies hook ran and path matches ${domain} domain.`,
    );
  }
  return deps[domain];
}

/**
 * Type definitions for domain dependencies
 */
export interface DomainDependencies {
  attestations: AttestationsDomainModule;
  audit: AuditDomainModule;
  consents: ConsentsDomainModule;
  directory: DirectoryDomainModule;
  disputes: DisputesDomainModule;
  identity: IdentityDomainModule;
  screening: ScreeningDomainModule;
  settlement: SettlementDomainModule;
  subjects: SubjectsDomainModule;
}

export function clearDomainDependencyCache(domain: string): void {
  const cacheKey = getCacheKey(domain);
  dependencyCache.delete(cacheKey);
}

export function clearAllDomainDependencyCaches(): void {
  dependencyCache.clear();
}

/**
 * Convenience helpers for each domain (type-safe)
 */
export function getAttestationsDeps(
  request: FastifyRequest,
): DomainDependencies["attestations"] {
  return getDomainDeps(request, "attestations");
}
export function getAuditDeps(
  request: FastifyRequest,
): DomainDependencies["audit"] {
  return getDomainDeps(request, "audit");
}
export function getConsentsDeps(
  request: FastifyRequest,
): DomainDependencies["consents"] {
  return getDomainDeps(request, "consents");
}
export function getDirectoryDeps(
  request: FastifyRequest,
): DomainDependencies["directory"] {
  return getDomainDeps(request, "directory");
}
export function getDisputesDeps(
  request: FastifyRequest,
): DomainDependencies["disputes"] {
  return getDomainDeps(request, "disputes");
}
export function getIdentityDeps(
  request: FastifyRequest,
): DomainDependencies["identity"] {
  return getDomainDeps(request, "identity");
}
export function getScreeningDeps(
  request: FastifyRequest,
): DomainDependencies["screening"] {
  return getDomainDeps(request, "screening");
}
export function getSettlementDeps(
  request: FastifyRequest,
): DomainDependencies["settlement"] {
  return getDomainDeps(request, "settlement");
}
export function getSubjectsDeps(
  request: FastifyRequest,
): DomainDependencies["subjects"] {
  return getDomainDeps(request, "subjects");
}
