/**
 * Handlers for Consent
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: consents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ConsentsDomainModule } from "../dependencies/consents-ddd.dependencies.js";
import type { CreateConsentGrantInput, GetConsentGrantInput, ListConsentGrantsInput } from "@kyvora/services/consents";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/consents
 * Operation: listConsentGrants
 */
export async function listConsentGrants(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], subjectId?: string | string[], relyingPartyId?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ConsentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListConsentGrantsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.consents.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/consents
 * Operation: createConsentGrant
 */
export async function createConsentGrant(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ConsentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateConsentGrantInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.consents.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/consents/{consentId}
 * Operation: getConsentGrant
 */
export async function getConsentGrant(
  request: FastifyRequest<{ Params: { consentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ConsentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetConsentGrantInput = {
    consentId: request.params.consentId,
  };
  const result = await deps.useCases.consents.get.execute(input);
  return reply.code(200).send(result);
}


