/**
 * DownloadEvidencePack handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { downloadEvidencePack } from "@kyvora/api-server/domains/audit/handlers";
import type { AuditDDDDependencies } from "@kyvora/api-server/domains/audit";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@kyvora/tests/shared";
import { AUDIT_USE_CASES } from "../__factories__/use-cases.js";

describe("DownloadEvidencePack", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AuditDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AuditDDDDependencies>(
      AUDIT_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeDownloadEvidencePack, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { packId: entity.id };

    await downloadEvidencePack(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeDownloadEvidencePack.execute).toHaveBeenCalledWith(expect.objectContaining({ packId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { packId: nonExistentId };
    
    vi.spyOn(mockDeps.executeDownloadEvidencePack, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      downloadEvidencePack(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
