/**
 * IdentityProvider DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * IdentityProvider DTOs
 *
 * DDD: Application DTOs for IdentityProvider use cases.
 */
import type { GetIdentityProviderParams, ListIdentityProvidersParams, RegisterIdentityProviderRequestInput } from "@kyvora/core/directory/types";
export type ListIdentityProvidersInput = ListIdentityProvidersParams;
export type RegisterIdentityProviderInput = RegisterIdentityProviderRequestInput;
export type GetIdentityProviderInput = GetIdentityProviderParams;
export type ListIdentityProvidersOutput = {};
export type RegisterIdentityProviderOutput = {};
export type GetIdentityProviderOutput = {};
