/**
 * Suspend DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: directory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * Suspend DTOs
 *
 * DDD: Application DTOs for Suspend use cases.
 */
import type { SuspendIdentityProviderParams, SuspendIdentityProviderRequestInput, SuspendRelyingPartyParams, SuspendRelyingPartyRequestInput } from "@kyvora/core/directory/types";
export type SuspendIdentityProviderInput = SuspendIdentityProviderParams & SuspendIdentityProviderRequestInput;
export type SuspendRelyingPartyInput = SuspendRelyingPartyParams & SuspendRelyingPartyRequestInput;
export type SuspendIdentityProviderOutput = {};
export type SuspendRelyingPartyOutput = {};
